### PR TITLE
TensorBoard 2.1.1

### PR DESCRIPTION
**Pull request by bileschi**
Cherrypicks:

  - 04401e8d Fix spuriously failing grpc test
  - e5332092 uploader: export experiment metadata (#3308)
  - d82e181e uploader: require experiment metadata from server (#3310)
  - b772612a uploader: remove inoperative `f`-string (#3311)
  - b0044160 uploader: export experiments to subdirectories (#3307)
  - c85ddb93 uploader: fix rate limiting for logdir polling (#3305)
  - 75e5d594 uploader: only send data for allowed plugins (#3300)
  - a3811724 uploader: factor test defaults into helpers (#3304)
  - 2a9319b3 uploader: add `PluginControl` handshake protos (#3299)
  - 2887aa3d Support experiment name and description in uploader (#3277)
  - 47f11fac Add trailing newline (#3267)
  - c02aad68 Refactor uploader to ease adding new data types (#3215)
  - b04c2e11 Extract Experiment/ExperimentMask messages into experiment.proto (#3255)
  - fca76cb4 Add wall_time field to GetOrCreateBlobSequenceRequest (#3253)
  - 0bbb22f4 Add the WriteBlob bidirectional streaming RPC to the write service. (#3226)
  - f330db35 Update export/write services for eventual tensor storage (#3236)
  - 272b690b Proto changes to support experiment name & description. (#3234)
  - b76fa082 add lint check against PY2 BUILD targets (#3220)
  - 231d782f uploader: make `util_test` py3-compatible internally (#3179)
  - 1a7dadea Silence deprecation warning spam about tf_record_iterator (#3319)
  - de236087 Change EventFileLoader to use tf_record_iterator when possible (#3185)
  - 2b9df536 When available, use inspect.getfullargspec instead of inspect.getargspec. (#3116)
  - 2ad7c654 black: reformat directory tensorboard/backend/event_processing
  - b7820660 black: reformat directory tensorboard/uploader
  - d78b7965 pylint: remove `g-import-not-at-top` suppressions (#3022)
  - 5dc9983b Convert BaseResponse to wrappers.BaseResponse (#3230)
  - 42a7f515 ci: remove Python 2.7 from `.travis.yml` (#3094)

The bulk of these are feature additions to the uploader to support
experiment name and description metadata. This also includes
compatibility changes to use `tf_record_iterator` rather than SWIG
bindings.

This release has new features, but is a patch release in order to
maintain cadence with TensorFlow.

### CODE REVIEW

**Comment by wchargin** [comment]
Let’s make sure to merge **with rebase**, not squash.

**Comment by wchargin** [comment]
Build broken; #3311 is an immediate fix (can cherry-pick). [TensorFlow’s
public Python 2 policy][1] is that patch releases will not have Python 2
packages, so we should also feel empowered to drop Python 2 support with
TensorBoard 2.1.1, but it may end up being simpler to just continue with
the existing build/CI/PyPI setup for this patch release. Either is fine
with me.

[1]: https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/ifEAGK3aPls

**Comment by wchargin** [comment]
> Hmm, could we change the first commit (g-import-not-at-top) so that we
> just apply the subset that affects the uploader tree?

That would be fine with me.

@bileschi: One way to do this would be to interactively rebase the
branch, change the `pick b152de4a pylint: ...` line on the second line
of the rebase plan to `edit b152de4a pylint: ...`, run

```
git checkout HEAD^ ':!tensorboard/uploader/`
```

to check out the old versions of all the non-uploader code, then run
`git commit --amend` to update the commit (and preferably add a short
message indicating what was changed), then `git rebase --continue`.
You’ll need to `git push --force-with-lease bileschi 2.1` after
rewriting those commits.

**Comment by wchargin** [comment]
Please cherry-pick #3320 to fix Python 3.5 release. (Verified fixed in a
Python 3.5 virtualenv with TensorBoard from head and TensorFlow at
either `tf-nightly` or `tensorflow==2.1.0`.)

**Comment by nfelt** [comment]
Let's also cherry pick #3185 (fixes this release to work with upcoming TF 2.2.0+) and #3319 (followup to that PR that avoids console spam).

**Comment by bileschi** [comment]
All CPs were googler-authored.

**Pull request merged**
