### PR TITLE
docs: update profiler tutorial

### PR DESCRIPTION
**Pull request by anirudh161**
* Motivation for features / changes:
1. Saved the notebooks with outputs enabled (and private outputs disabled) as a workaround to prevent broken iframes rendering on tensorflow.org
2. Made some minor text changes and added a link to the Dev Summit 2020 talk

### CODE REVIEW

**Comment by wchargin** [comment]
For context, this supersedes #3441.

**Comment by anirudh161** [comment]
That's weird. The outputs were there before I ran nbfmt.py on the notebook. Let me look into it and submit another commit

**Comment by wchargin** [comment]
As I [mentioned on #3441][1], make sure that `private_outputs: false` is
set in the notebook to preserve the contents. If you have a notebook
with output cells, you can set that easily by running `nbfmt.py` on the
notebook and passing `--preserve_outputs`. This will write the option
into the notebook so that future `nbfmt.py` runs know not to remove
them, even when the flag is not passed.

It doesn’t look like `private_outputs: false` was set at any point in
this change, but it also doesn’t look like the outputs were saved. The
“Formatted notebook with nbfmt” commit has a delta of 111 insertions and
110 deletions (i.e., just sorted keys and fixed trailing newline), and
you can see from the diff that it didn’t actually remove any outputs
(they were all `outputs: []` already).

[1]: https://github.com/tensorflow/tensorboard/pull/3441#issuecomment-606732347

**Comment by anirudh161** [comment]
I was so sure I saved the outputs then! Guess I didn't after all :) I added another commit with outputs saved

**Comment by anirudh161** [comment]
That's a good point. I fixed the cache entries and added a new commit

**Comment by wchargin** [comment]
Awesome; thanks! Tested; this works for me both before and after running
the notebook.

I’ll go ahead and merge this now.

**Pull request merged**
