### PR TITLE
Minimal working version of TF in responsive mode

### PR DESCRIPTION
**Pull request by stephanwlee**
Having some responsive layout generally is a good idea and we have gotten few
request for it in #1412. This change does not optimize the experience to the finest\
detail but simply lay dashboard out in vertical manner.
image

### CODE REVIEW

**Comment by stephanwlee** [comment]
It should now be ready for review :)

**Comment by bhack** [comment]
News?

**Comment by Tzeny** [comment]
I think this is really relevant for ML in production

**Comment by finngaida** [comment]
Hey @stephanwlee what happened to this PR, did you end up using another solution?

**Pull request closed without merging**
