### PR TITLE
Removed redundant lines from `get_started.ipynb`

### PR DESCRIPTION
**Pull request by ManishAradwad**
Fixes : #3451 
@lamberta Can you plz review this PR.

### CODE REVIEW

**Comment by lamberta** [comment]
Hi @ManishAradwad , to make the diffs easier to read, you can try running the notebook through [nbfmt.py](https://github.com/tensorflow/docs/blob/master/tools/nbfmt.py) or downloading from Colab.

**Comment by wchargin** [comment]
@lamberta: Thanks for the pointer to `nbfmt.py` (and thanks, apparently,
for writing it!). That looks like it would make things a bunch easier
for us. I’ll send a PR to reformat our docs and add that to CI.

**Comment by lamberta** [comment]
@wchargin Cool, let me know how it goes. Now looking at ways to integrate it into the GitHub CI to reduce friction for tensorflow/docs PRs

**Comment by wchargin** [comment]
Opened #3455, which does integrate into GitHub Actions. It’s pretty
painless (totally sufficient for me), though it would be even painlesser
if you made a GitHub Action that we could just depend on instead of
having to `wget` the file and `pip install absl-py` ourselves. :-)

**Comment by wchargin** [comment]
@ManishAradwad: I’ve merged #3455; please feel free to update this PR
(after rebasing on master) at your convenience.

**Comment by ManishAradwad** [comment]
@wchargin Thanks for the review. I'm unable to resolve the conflicts of this branch with the master branch(apparently the nb is not opening in vscode). I think to avoid any complexity, it would be better if I close this PR and open another one. I'll send one soon. 
Thanks!

**Comment by ManishAradwad** [comment]
@wchargin I've created another PR at https://github.com/tensorflow/tensorboard/pull/3459 
Plz review it

**Pull request closed without merging**
