### PR TITLE
Remove URL guard ?debugger_data=enabled

### LINKED ISSUE #274: Debugging features in the graph dashboard are broken.
Internal debugging features are broken because the `_debuggerDataEnabled` property is [no longer passed to the graph dashboard](https://github.com/tensorflow/tensorboard/blob/530310dd26f8f14df7a49b6d8f286c3d63627e0d/tensorboard/components/tf_tensorboard/tf-tensorboard.html#L366). With that property set to false, no debugging features appear.

A long term reality is that the debugger plugin has its own dashboard. For now, we can fix the breakage by having the graph dashboard rely on the `plugins_listing` route to determine whether there is debugging data to visualize. This means that debugging features appear in the graph if the backend (the debugger plugin) detects debugger-related events.

### PR DESCRIPTION
**Pull request by chihuahua**
Previously, internal debugging features were guarded by whether ?debugger_data=enabled was present in the URL. This change makes the graph dashboard request a response from the plugins_listing route and then check if the debugger plugin is enabled.

This is more in line with how other features are guarded within TensorBoard. This also fixes how debugging features are currently broken in TensorBoard because the debuggerDataEnabled boolean property is not passed to the graph dashboard; With this change, the graph dashboard does not even depend on that property being passed to the graph dashboard.

This PR fixes #274.

### CODE REVIEW

**Comment by caisq** [comment]
(this comment is to cc myself) 
Thanks for submitting the fixing PR, @chihuahua !

**Comment by caisq** [comment]
gentle ping @jart @wchargin @dandelionmane ?

**Comment by wchargin** [comment]
I'll take a look1

**Comment by chihuahua** [comment]
I also agree. The current plan is to build a frontend for the debugger plugin, which needs the tf-graph component, but not the left sidebar containing runs and other widgets. Then, the graph dashboard will only communicate with its own backend.

**Comment by wchargin** [comment]
That's fine with me.

**Pull request merged**
