### PR TITLE
Delete runs-table-component and lots of old hparams-related code.

### PR DESCRIPTION
**Pull request by bmd3k**
Delete the following now that they are unused:
- runs_table_component, since this is no longer used in practice.
- anything in runs_effects, runs_data_source related to hparam retrieval.
- runs state's fields related to sorting and pagination
- hparams state's `spec` and `filters` fields.
- runsTableShown action, which now leads to unnecessary hparams requests
- anything else i could find depending on the previous four or orphaned by deleting the previous four.

### CODE REVIEW

**Comment by bmd3k** [comment]
Note that I don't plan to merge this until a week of "no runs table in experiment list" in prod.

**Comment by JamesHollyer** [comment]
> Note that I don't plan to merge this until a week of "no runs table in experiment list" in prod.

I think we should wait 2 weeks.

**Review by JamesHollyer — COMMENTED** [review]
It's. just. so. beautiful!

Did you ensure this does not break sync?

**Comment by bmd3k** [comment]
> > Note that I don't plan to merge this until a week of "no runs table in experiment list" in prod.
> 
> I think we should wait 2 weeks.

Ok, that's fine. Even if we merged this next Thursday we wouldn't be able to release until after Thanksgiving anyways. So I will aim to merge it Monday the 27th.

**Comment by bmd3k** [comment]
> It's. just. so. beautiful!
> 
> Did you ensure this does not break sync?

Yes!

**Review by JamesHollyer — APPROVED** [review]

**Pull request merged**
