### PR TITLE
Make metanodes out of functions in the graph explorer

### PR DESCRIPTION
**Pull request by chihuahua**
Previously, the graph explorer had visualized nodes that represented function calls as op nodes, which was not helpful because that showed none of the logic within the function.

This change makes it so that the graph explorer parses the library of GraphDefs and visualizes each function call as a metanode. Functions can recursively call functions, so we introduce a means for the graph hierarchy to dynamically change. This is done via first creating a metanode for each function and then making a copy of a function's metanode and injecting that copy into a meta graph when necessary (ie, when the user expands a node with a function).

There is still much work to be done. We need to make it clear that the metanodes represent functions. We need to enumerate the places in which each function is called. We should also visually indicate that 2 metanodes represent the same function if they do (perhaps via filling the nodes with the same color). However, this PR lays down the code organization that at least allows functions to be visualized.

Here is a screenshot that shows 2 nodes that represent functions. They are both expanded.

efddh6jswhy

### CODE REVIEW

**Comment by dsmilkov** [comment]
Thanks Chi! This is a great start. Quick UI q: in the screenshot you shared seems like function names always have a random hex suffix, can we strip that out when showing the node to the user and maybe show it in alt="" ?

---

Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tensorboard/plugins/graph/tf_graph_common/graph.ts, line 59 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrH80Ta76XVHh4HrruF:-KrH80Ta76XVHh4HrruG:b-pu3i1i) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/graph.ts#L59)):*
> ```XML
>   isReferenceEdge: boolean;
>   /** The index of the output tensor of the source node. */
>   outputTensorIndex: string;
> ```

Any reason why changing this from number -> string?

---

*[tensorboard/plugins/graph/tf_graph_common/graph.ts, line 79 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrH8TmNIQvivPfb7q7H:-KrH8TmNIQvivPfb7q7I:b-k1fzeo) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/graph.ts#L79)):*
> ```XML
>   name: string;
>   /** The index of the output tensor of the source node. */
>   outputTensorIndex: string;
> ```

same here, see previous comment about number -> string

---

*[tensorboard/plugins/graph/tf_graph_common/graph.ts, line 163 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrH9XZlCCqIpdiozF2A:-KrH9K2YwFJS581zYT-0:b-dw24fr) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/graph.ts#L163)):*
> outputShapes: {[key: string]: TensorShape;};

strange to have outputShapes be strings. Can you separate this in two fields, e.g. `outputShapes` and `outputNames`?

---

*[tensorboard/plugins/graph/tf_graph_common/graph.ts, line 768 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrH9zpLJUuTKbIgZGQz:-KrH9zpLJUuTKbIgZGR-:by1jel4) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/graph.ts#L768)):*
> ····

remove spaces\tabs

---

*[tensorboard/plugins/graph/tf_graph_common/proto.ts, line 55 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrHB6fpZjsKCfA1CAD2:-KrHB6fpZjsKCfA1CAD3:byhsn8u) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/proto.ts#L55)):*
> Specifies an argument.

Can you add little more detail what an argument is. E.g. part of tensorflow functions,  there are input and output arguments etc.

---

*[tensorboard/plugins/graph/tf_graph_common/proto.ts, line 63 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrHBoc7puH7uQrRadlL:-KrHBoc7puH7uQrRadlM:b-ikx82p) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/proto.ts#L63)):*
> ```XML
> 
>   /**
>    * Describes a function.
> ```

Update comment. 

---

*[tensorboard/plugins/graph/tf_graph_common/render.ts, line 582 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrHC8WchA_PM-4wQ2PE:-KrHC8WchA_PM-4wQ2PF:b-a0f172) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/render.ts#L582)):*
> ······

remove whitespace

---

*[tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html, line 120 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrHCoKwYOE0705RFkkN:-KrHCoKwYOE0705RFkkO:b81ai6m) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html#L120)):*
> !graph || !graph['node']

does `fetchAndParseGraphData` sometimes return `parsedObj['node']` and sometimes the full `parsedObj` ? if it always returns `parsedObj`, here we shouldn't check for `|| !graph['node']`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-:-KrHDoVKoPPLfkJyqCmt:by7gk1j)*

**Comment by chihuahua** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[tensorboard/plugins/graph/tf_graph_common/graph.ts, line 59 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrH80Ta76XVHh4HrruF:-KrHxvXMzPbUn6Lp7Ang:b-yo5ipu) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/graph.ts#L59)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Any reason why changing this from number -> string?
</blockquote></details>

Nodes within functions look like this: op_name:output_key:42

where "output_key:42" together expresses the output slot, so a number is no longer enough.

---

*[tensorboard/plugins/graph/tf_graph_common/graph.ts, line 79 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrH8TmNIQvivPfb7q7H:-KrHyOoYdDoUpOxdhf_A:b34f2pl) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/graph.ts#L79)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

same here, see previous comment about number -> string
</blockquote></details>

Per above.

---

*[tensorboard/plugins/graph/tf_graph_common/graph.ts, line 163 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrH9XZlCCqIpdiozF2A:-KrHyRpY0SB08cb9xF_h:b-ixjdsc) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/graph.ts#L163)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> outputShapes: {[key: string]: TensorShape;};

strange to have outputShapes be strings. Can you separate this in two fields, e.g. `outputShapes` and `outputNames`?
</blockquote></details>

Previously, outputShapes was an array of TensorShapes (lists of numbers). Other code would index into the array to get the TensorShape for a numeric output slot. I changed into an object because output slots are now strings that are more than numbers.

---

*[tensorboard/plugins/graph/tf_graph_common/graph.ts, line 768 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrH9zpLJUuTKbIgZGQz:-KrHytq3ucF1S9FVMxxA:b-896fix) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/graph.ts#L768)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> ····

remove spaces\tabs
</blockquote></details>

Done.

---

*[tensorboard/plugins/graph/tf_graph_common/proto.ts, line 55 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrHB6fpZjsKCfA1CAD2:-KrHzqTXYa6-eArdETb-:b-896fix) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/proto.ts#L55)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> Specifies an argument.

Can you add little more detail what an argument is. E.g. part of tensorflow functions,  there are input and output arguments etc.
</blockquote></details>

Done.

---

*[tensorboard/plugins/graph/tf_graph_common/proto.ts, line 63 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrHBoc7puH7uQrRadlL:-KrHzxVlOzth8qZ95b3G:b-896fix) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/proto.ts#L63)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

Update comment. 
</blockquote></details>

Done.

---

*[tensorboard/plugins/graph/tf_graph_common/render.ts, line 582 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrHC8WchA_PM-4wQ2PE:-KrI-6C90zCX6xmvpEgH:b-896fix) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_common/render.ts#L582)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> ······

remove whitespace
</blockquote></details>

Done.

---

*[tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html, line 120 at r2](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-KrHCoKwYOE0705RFkkN:-KrIGzsNp06Pb-NDceFn:b-27aa4t) ([raw file](https://github.com/tensorflow/tensorboard/blob/4e14c160718dcc69b1e6998930bb33a47b8c9fa9/tensorboard/plugins/graph/tf_graph_loader/tf-graph-loader.html#L120)):*
<details><summary><i>Previously, dsmilkov (Daniel Smilkov) wrote…</i></summary><blockquote>

> !graph || !graph['node']

does `fetchAndParseGraphData` sometimes return `parsedObj['node']` and sometimes the full `parsedObj` ? if it always returns `parsedObj`, here we shouldn't check for `|| !graph['node']`
</blockquote></details>

I realized that `graph` is never falsy here, so `!graph.node` is all we need to check - `graph.node` is undefined if the pbtxt lacks node attributes. For instance:

```
foo {
}
```

If the pbtxt is empty, we actually  show no clear indication of that, which I deem to be a bug. I filed an issue to be fixed separately: https://github.com/tensorflow/tensorboard/issues/346

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/341)*

**Comment by dsmilkov** [comment]
:lgtm:

---

Reviewed 6 of 6 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-:-KrJH3-6K8FfzjsDvkyk:bnfp4nl)*

**Comment by dsmilkov** [comment]
:lgtm_strong: 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/341#-:-KrLc9IX8wOy_w4wRje4:b-uwkowd)*

**Comment by chihuahua** [comment]
Hmm, that's odd. I don't think the LGTM through Reviewable made it into GitHub.

**Pull request merged**
