### PR TITLE
ci: discontinue TensorFlow 1.x environment

### PR DESCRIPTION
**Pull request by wchargin**
Summary:
Now that all the 1.x-only tests have been ported or removed (#1705), we
have no need to run tests against TF 1.x. We’re at TensorBoard 2.3 at
this point, and we don’t offer TF 1.x compatibility for future releases.

Test Plan:
Verify that this Travis build creates only two jobs instead of three.

wchargin-branch: tf2x-only

### CODE REVIEW

**Comment by nfelt** [comment]
Hmm, one other thought: I'm realizing that turning off this CI effectively renders any TF 1.x-only tests (i.e. tests using `run_v1_only`) dead code.  That's not really ideal; we should preferably clean up the tests before disabling them entirely or we risk just having them hang around forever.

Cleaning up could either mean converting to `tf.compat.v1.*` symbols so they can still run against TF 2.0, if the tests are still useful (see also #1718) or it could mean deleting them entirely.

**Comment by wchargin** [comment]
Okay; that’s reasonable. Cleaning up these tests seems feasible, but
isn’t high priority for me right now, so (per discussion) we’ll leave
this PR alone for now.

**Comment by wchargin** [comment]
Update: TensorFlow and TensorBoard 2.0.0 are out, and nearly all of our
tests work on TensorFlow 2.x. The stragglers are Beholder and the
experimental DB mode (used in the core plugin and scalars only). For
details, see #1705 and comments therein.

**Comment by stephanwlee** [comment]
Is this PR still relevant? If not, let's close it.

**Comment by wchargin** [comment]
Now that Beholder’s gone, we actually have no more `run_v1_only` tests,
so I can resurrect this and kill the TF 1.x dependency (which is no
longer a nightly as of #2769, but still exists).

**Comment by wchargin** [comment]
Yep, that sounds good to me.

**Pull request merged**
