### PR TITLE
chore: Upgrade prettier from 2.1.1 to 2.4.1

### PR DESCRIPTION
**Pull request by bileschi**
* Motivation for features / changes
Support for `override` keyword.   Googlers see b/197297512

* Technical description of changes
Upgrade `prettier` to 2.4.1 and run `yarn fix-lint`

### CODE REVIEW

**Comment by nfelt** [comment]
Could I trouble you to split this into 3 commits and merge with rebase-and-merge, like what William did here? https://github.com/tensorflow/tensorboard/pull/4122

That lets us cleanly add the middle commit (with the formatting changes only) to `.git-blame-ignore-revs` (ref: https://github.com/tensorflow/tensorboard/pull/4123)

**Comment by bileschi** [comment]
> Could I trouble you to split this into 3 commits and merge with rebase-and-merge, like what William did here? #4122
> 
> That lets us cleanly add the middle commit (with the formatting changes only) to `.git-blame-ignore-revs` (ref: #4123)

No problem - done.

**Review by bmd3k — APPROVED** [review]
I assume there will be followup https://github.com/tensorflow/tensorboard/pull/4123, which you can assign to me for review if you'd like.

**Comment by bileschi** [comment]
@bmd3k yes, will do.  Thanks also for the review.
@nfelt rebasing & merging

**Pull request merged**
