### PR TITLE
change tensorboard_html_binary noinline attr from string list to label

### PR DESCRIPTION
**Pull request by jameswex**

### CODE REVIEW

**Comment by wchargin** [comment]
Justine is the right person to review this, but she's OOO until Monday.

The change looks fine to me, though I'm not too familiar with this code. If this is time-sensitive, I can approve and merge it now. What would you like?

**Comment by jameswex** [comment]
No need to rush to merge this, but thanks for the review.

Any idea why the CI failed?

**Comment by wchargin** [comment]
Yep: CI failure fixed in #338; if you rebase onto master and re-push, tests should pass.

**Comment by jart** [comment]
Thank you. We'll have this imported into the internal repository in the next few days.

**Pull request merged**
