### PR TITLE
Merge Beholder into TensorBoard

### PR DESCRIPTION
**Pull request by chrisranderson**
@jart recommended just copying the files over at first without integrating things, so here are the copies. :)

### CODE REVIEW

**Comment by chrisranderson** [comment]
I'll take a look at fixing the paths tomorrow.

**Comment by jart** [comment]
Thank you Chris. We have two options:

1. (Preferred) Update the BUILD files with the new path structure, etc. so that `bazel test //tensorboard/...` passes. We can't merge unless Travis is green.

2. Move beholder from `tensorboard/plugins` to `third_party/beholder` which side-steps the issue entirely, as that directory is not tested by Travis.

**Comment by chrisranderson** [comment]
The paths look good, but my tests fail (likely because I'm expecting a certain directory to already exist, I'm thinking). I have not much time nowadays - I'm thinking I'll just remove the tests for now.

**Comment by chrisranderson** [comment]
@jart The copy-pasted ffmpeg stuff is an issue still, right?

**Comment by jart** [comment]
Yes. The code written by the other guy looks super trivial to replace. Is there any chance you could just whip up a quick non-general private function to do what it's doing, so that file can be removed?

**Comment by chrisranderson** [comment]
:) Woo hoo! You're welcome. May tons of people learn and benefit from it.

**Comment by mholt** [comment]
I know our lab will! I'm gonna use this as soon as it's in the regular pip package. Any idea when (or with which release) that will be?

**Comment by jart** [comment]
Beholder will most likely be released in TensorBoard 0.5 alongside TensorFlow 1.5. My best guess for when that would happen is January.

I don't expect you to wait that long. So I just registered [tb-nightly](https://pypi.python.org/pypi/tb-nightly) which will be [tf-nightly](https://pypi.python.org/pypi/tf-nightly)'s doppelganger. Once I'm done putting some polish on Chris' amazing work, I'll write a cron script to update that package, so you can start using it right away (without having to build from source.)

cc: @gunan

**Comment by mholt** [comment]
Sounds amazing, thank you!!

**Pull request merged**
