### PR TITLE
add path_prefix_from_file option, adding security by obscurity. This …

### PR DESCRIPTION
**Pull request by joveh**
…option is helpful on multi-user systems.

* Motivation for features / changes
https://github.com/tensorflow/tensorboard/issues/267#issuecomment-671820015

We noticed open tensorboards on our shared systems 

* Technical description of changes

* Screenshots of UI changes

* Detailed steps to verify changes work correctly (as executed by you)
path_prefix_from_file is an alternativ to path_prefix, if both are given path_prefix will be used

* Alternate designs / implementations considered
It would be nice to have a config-file implementation with all options for tensorboard, mybe using json or yaml format

### CODE REVIEW

**Review by tz-rrze — APPROVED** [review]
A simple but really helpful addition to make TensorBoard usable on a shared multi-user system without severe security concerns! Solves a long standing security issue.

**Comment by tz-rrze** [comment]
@yoshipon: you correctly mentioned in https://github.com/tensorflow/tensorboard/issues/267#issuecomment-671820015 on a suggestion form @jdhayes that `--path_prefix` itself is still insecure on a multi-user system; I hope you like the new approach in this PR to read the hash from a file :-)

**Comment by ericdnielsen** [comment]
We believe the comment https://github.com/tensorflow/tensorboard/issues/267#issuecomment-415829957 is still governing on changes/features requests along these lines.

**Comment by mahendrapaipuri** [comment]
We are facing a similar issue at our HPC center. This is already a good step forward to run TensorBoard on multi-user environment. Is it possible to use the approach of JupyterLab here by providing the path prefix as a token and user needs that token to access TensorBoard?

**Comment by jdhayes** [comment]
Yes, I agree. HPC facilities cannot use NGINX, as the localhost is still exposed to all users on the node. Just a note, that if anyone was going to make it as a service, then NGINX would be a good option to add real authentication.

The Jupyter hash/token is a good method for HPC facilities to obscure the URL such that users do not accidentally intrude. Malicious users are less of an issue, but even they would have difficulty finding the address if a hash/token was added.

If reading from a file is not acceptable, could the `--path_prefix` take the value from an environment variables if not provided on the command line?

**Comment by joveh** [comment]
> Yes, I agree. HPC facilities cannot use NGINX, as the localhost is still exposed to all users on the node. Just a note, that if anyone was going to make it as a service, then NGINX would be a good option to add real authentication.
> 
> The Jupyter hash/token is a good method for HPC facilities to obscure the URL such that users do not accidentally intrude. Malicious users are less of an issue, but even they would have difficulty finding the address if a hash/token was added.
> 
> If reading from a file is not acceptable, could the `--path_prefix` take the value from an environment variables if not provided on the command line?

Please have a look at https://github.com/tensorflow/tensorboard/pull/5570

**Comment by yoshipon** [comment]
@tz-rrze @joveh Thank you for making effort for the problems with HPC systems, and I'm sorry for my late reply.
Although it is unfortunate that this kind of PR does not seem to be merged, I agree that the main developers do not want to increase the security risk of this OSS.

I was using the following `tensorboard-hash` command, which makes no change on the `tensorboard` itself.
```python
#! /usr/bin/env python3

import re
import sys
import uuid
from tensorboard.main import run_main

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.argv += ["--path_prefix", f"/{uuid.uuid4().hex}"]

    sys.exit(run_main())
```

However, now I'm not using this hack because (at least some old versions of) RustBoard, which makes awesome performance improvements of TensorBoard, seemed to communicate with the main process through an unauthenticated TCP/IP connection.
I respect for the main developer's policy, and now I'm running TensorBoard on my local PC by mounting the HPC's filesystem with `sshfs`.

**Pull request closed without merging**
