### PR TITLE
Projector: Semi-supervised t-SNE

### PR DESCRIPTION
**Pull request by francoisluus**
Add to the projections-panel a supervise factor slider, an unlabeled class specifier and a supervise column specifier. Capture the events and update the dataset t-SNE variables that will be used to alter the projections. Add a supervision clause to t-SNE to incorporate pairwise prior probabilities based on label differences and similarities.

~Demo here: http://tensorserve.com:6016~
```bash
git clone https://github.com/francoisluus/tensorboard-supervise.git
cd tensorboard-supervise
git checkout  4b726e0a69e2fbd1e671a26ba19eea2d928e0eaf
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6016
```
### Pairwise label similarity priors
Notice the repeating contraction in the below image, relating to repetitively turning supervision on and off, which incorporates the prior probabilities based on pairwise label similarity/dissimilarity when supervision is turned on.
projector-tsne-supervise-vid1-red2-size2
### Design and behavior
1. When the supervision slider is set to 0, t-SNE functions exactly as before as the supervision clause is not entered.
2. The supervision slider sets the label importance value in range [0, 1], where 0 turns off supervision and 1 sets full label importance. The concept of label importance is used from McInnes et al. [1] and welcoming comments from @lmcinnes .
3. The supervision slider changes a visible percentage value from 0 to 100, corresponding to label importance values of 0 to 1.
4. An unlabeled class label, also known as an ignored label can be specified, which would consider corresponding points as unlabeled points that receive a default pairwise prior probability.
5. A supervise column specifier gets the metadata column to use to determine which labels the supervision is conducted with.
6. t-SNE does cause some unexpected behavior when choosing a metadata column with many hundreds of classes, then a re-run is required.
7. Changes in the supervision settings are updated first in the dataset class, and then propageted to the TSNE class itself to use in the gradient step function, where a snapshot is made to prevent supervision changes during the step (not 100% sure if deep copy actually happens).
8. The supervision settings may change from step to step, e.g. such that one step may include supervision while the next step is without supervision, i.e. if the user slides the supervision factor from a non-zero value to zero.

### Semi-supervised t-SNE
1. The pairwise prior probabilities are set according to McInnes et al. [1], where neighbors are used and where current labeling is not representative of class prior probabilities.
2. However, the normalization is computed over all pairwise prior probabilities according to Yang et al. [2], and not only within neighborhoods as in [1].
3. The naive pairwise prior probability is 1/N, which is used for interactions with unlabeled class samples.
4. For different label pairs we subtract superviseFactor/otherCount from the naive prior, where otherCount is the number of samples with a different label, so if superviseFactor is sufficiently large the attractive force between two samples with different labels will be set to epsilon. Attractive force is easily zeroed between different labeled samples.
5. For same-label pairs we add superviseFactor/sameCount to the naive prior, and the maximum sum is limited close to 1. Attractive force scales up more gradually between same-label pairs.

### Semi-Supervised t-SNE of McInnes et al. [1]

From https://github.com/lmcinnes/sstsne/blob/master/sstsne/_utils.pyx :
```python
for i in range(n_samples):
    sum_Pi = 0
    if using_neighbors:
        for k in range(K):
            j = neighbors[i, k]
            n_same_label = label_sizes[labels[i] + 1]
            n_other_label = n_samples - n_same_label - n_unlabelled
            if rep_samples:
                ...
            else:
                if labels[i] == -1 or labels[j] == -1:
                    prior_prob = 1.0 / n_samples
                elif labels[j] == labels[i]:
                    prior_prob = min((1.0 / n_samples) + (label_importance / n_same_label), 1.0 - EPSILON_DBL)
                else:
                    prior_prob = max((1.0 / n_samples) - (label_importance / n_other_label), EPSILON_DBL)
            P[i, j] *= prior_prob
            sum_Pi += P[i, j]
        for k in range(K):
            j = neighbors[i, k]
            P[i, j] /= sum_Pi
```

### Attraction normalization of Yang et al. [2]

From Yang et al. [1] the attractive and repulsive forces in weighted t-SNE are balanced with a connection scalar:

where the connection scalar is given as 
The issue here is that if the sum of the prior probabilities are small, then the effective gradient gets scaled down accordingly, which is the case here with a nominal prior of 1/N. So we normalize the gradient size by dividing with the sum of prior probabilities and leaving the repulsion normalization unaffected:

Note that the result here is shown for weighted t-SNE, but it holds for normal t-SNE and its Barnes-Hut implementation.

```typescript
    let sum_pij = 0;
    let forces: [number[], number[]][] = new Array(N);
    for (let i = 0; i < N; ++i) {
      let pointI = points[i];
      if (supervise) {
        var sameCount = labelCounts[labels[i]];
        var otherCount = N - sameCount - unlabeledCount;
      }
      // Compute the positive forces for the i-th node.
      let Fpos = this.dim === 3 ? [0, 0, 0] : [0, 0];
      let neighbors = this.nearest[i];
      for (let k = 0; k < neighbors.length; ++k) {
        let j = neighbors[k].index;
        let pij = P[i * N + j];
        if (supervise) {  // apply semi-supervised prior probabilities
          if (labels[i] == unlabeledClass || labels[j] == unlabeledClass) {
            pij *= 1. / N;
          }
          else if (labels[i] != labels[j]) {
            pij *= Math.max(1. / N - superviseFactor / otherCount, 1E-7);
          }
          else if (labels[i] == labels[j]) {
            pij *= Math.min(1. / N + superviseFactor / sameCount, 1. - 1E-7);
          }
          sum_pij += pij;
        }
    
    ...
    
    let A = 4 * alpha;
    if (supervise)
      A /= sum_pij;
    const B = 4 / Z;
```

### References
[1] Leland McInnes, Alexander Fabisch, Christopher Moody, Nick Travers, "Semi-Supervised t-SNE using a Bayesian prior based on partial labelling", https://github.com/lmcinnes/sstsne. 2016.

[2] Yang, Zhirong, Jaakko Peltonen, and Samuel Kaski. ["Optimization equivalence of divergences improves neighbor embedding"](http://proceedings.mlr.press/v32/yange14.pdf). International Conference on Machine Learning. 2014.

### CODE REVIEW

**Comment by francoisluus** [comment]
## Same-label zero repulse (Semi-supervised t-SNE with original space pairwise similarity priors)
This comment proposes a same-label zero repulse, in addition to the integration of label supervision as prior probabilities into the original space pairwise similarities. The branch proposing this additional constraint on t-SNE can be found here: https://github.com/tensorflow/tensorboard/compare/master...francoisluus:projector-tsne-supervise-repulseweight

The potential benefit of same-label zero repulse is more efficient use of limited t-SNE embedding space, as same-label clusters would pack more closely together. Greater liberty could be taken in also conditioning different-label pair repulsion at the risk of confusing or counteracting the delicate KL-divergence objective.

Demo here: http://tensorserve.com:6017
```bash
git clone https://github.com/francoisluus/tensorboard-supervise.git
cd tensorboard-supervise
git checkout  66aebdeba14777b777aaf328eced116380d0de98
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6017
```

### Original space pairwise similarity priors
Notice the repeating contraction in the below image, relating to repetitively turning supervision on and off, which incorporates the prior probabilities effectively in the attractive term when supervision is turned on. Note however that same-label clusters do not fully collapse and there remains some separation as there is still a repulsive force between same-label samples.
projector-tsne-supervise-vid1-red2-size2

### Same-label zero repulse and pairwise similarity priors
The contraction is intensified by zeroing the repulsion between same-label samples, resulting in higher collapse of same-label clusters.
projector-tsne-supervise-attractrepulseweight-vid1

### Same-label zero repulse only
Visually ascertain the effect of same-label zero repulse isolated in the below image, in the absence of pairwise similarity prior supervision. Note that there is a contraction when supervision is turned on, as any remaining repulsion between same-label samples are set to zero.
projector-tsne-supervise-repulseweight-vid2-red1

### Weighted t-SNE with pairwise conditionality
Yang et al. [1] proposed weighted symmetric SNE (ws-SNE), which introduces an external condition into s-SNE that depends on pairwise qualities _Mij_.



As before, the gradient update result in [1] is scaled by the sum of priors, now with the joint condition _Mij_ incorporated.



For _theta_=1 the weighted t-SNE gradient update is then used as follows.



### Same-label zero repulse: Barnes-Hut approximation
The Barnes-Hut speedup is too attractive to sacrifice, yet cell properties on quadtrees have to be independent of specific point-to-point qualities _Mij_. It is for this reason that _Mij_ is relaxed as in the below equation from [1] to _di*dj_ so that sufficiently distant cells can be summarized only according to constituent point properties, thereby retaining _NlogN_ complexity.



Supervision exerted as pairwise label similarity/dissimilarity _Mij_ suffers from this dependence that prevents full Barnes-Hut summarization. However, point-to-point interactions in Barnes-Hut can still be leveraged to affect proximal points in the embedding. Here we achieve this by operating in the point-to-point clause of Barnes-Hut algorithm:

```typescript
        // Squared distance from point i to cell.
        if (node.children == null ||
            (squaredDistToCell > 0 &&
             node.rCell / Math.sqrt(squaredDistToCell) < THETA)) {
            ...
        }
        // Cell is too close to approximate.
        let squaredDistToPoint = this.dist2(pointI, node.point);
        let qijZ = 1 / (1 + squaredDistToPoint);

        if (supervise) {
          let j = node.pointIndex;
          let Mij = 1.;

          if (!(labels[i] == unlabeledClass || labels[j] == unlabeledClass)
              && labels[i] == labels[j]) {
            Mij = 1. - superviseFactor;
          }
          Z += Mij * qijZ;
          qijZ *= Mij * qijZ;
        }
        else {
          Z += qijZ;
          qijZ *= qijZ;
        }
```
### References
[1] Yang, Zhirong, Jaakko Peltonen, and Samuel Kaski. ["Optimization equivalence of divergences improves neighbor embedding"](http://proceedings.mlr.press/v32/yange14.pdf). International Conference on Machine Learning. 2014.

**Comment by dsmilkov** [comment]
Reviewed 1 of 4 files at r1.
Review status: 1 of 4 files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[tensorboard/plugins/projector/vz_projector/bh_tsne.ts, line 494 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/724#-KywDdCxx7LOoe34GaAF:-KywDdCxx7LOoe34GaAG:b-7uk3w8) ([raw file](https://github.com/tensorflow/tensorboard/blob/26ea393839492148dc666129f3313e202d3c114e/tensorboard/plugins/projector/vz_projector/bh_tsne.ts#L494)):*
> ```XML
>     // Normalize the negative forces and compute the gradient.
>     let A = 4 * alpha;
>     if (supervise)
> ```

to be consistent with the rest of the codebase wrap if statements in {}, i.e.

```js
if (supervise) {
  A /= sum_pij;
}
```

---

*[tensorboard/plugins/projector/vz_projector/data.ts, line 369 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/724#-KywDEvzCTnIS83ukhpE:-KywDEvzCTnIS83ukhpF:b5wws46) ([raw file](https://github.com/tensorflow/tensorboard/blob/26ea393839492148dc666129f3313e202d3c114e/tensorboard/plugins/projector/vz_projector/data.ts#L369)):*
> ```XML
>       if (this.tsne.superviseColumn != superviseColumn) {
>         this.tsne.superviseColumn = superviseColumn;
>         console.log(this.tsne.superviseColumn);
> ```

remove console.log

---

*[tensorboard/plugins/projector/vz_projector/data.ts, line 377 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/724#-KywDCrYYVGcfY9Vd8Iz:-KywDCrZKrM1coOmPK5u:b5dvm4y) ([raw file](https://github.com/tensorflow/tensorboard/blob/26ea393839492148dc666129f3313e202d3c114e/tensorboard/plugins/projector/vz_projector/data.ts#L377)):*
> ```XML
>         this.tsne.labelCounts = labelCounts;
> 
>         let sampledIndices = this.shuffledDataIndices.slice(0, TSNE_SAMPLE_SIZE);
> ```

wrap to 80 width

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts, line 206 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/724#-KywDOFYZi7H76lBSG9d:-KywDOFYZi7H76lBSG9e:bdom6q6) ([raw file](https://github.com/tensorflow/tensorboard/blob/26ea393839492148dc666129f3313e202d3c114e/tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts#L206)):*
> ```XML
>       let numMatches = this.dataSet.points.filter(p =>
>           p.metadata[this.superviseColumn] == value).length;
>       
> ```

remove leading whitespace

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts, line 211 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/724#-KywDTcS2jrtWTU6bEHT:-KywDTcS2jrtWTU6bEHU:b5dvm4y) ([raw file](https://github.com/tensorflow/tensorboard/blob/26ea393839492148dc666129f3313e202d3c114e/tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts#L211)):*
> ```XML
>         this.dataSet.setTSNESupervision(this.superviseColumn, 0, '');
>       } else {
>         this.unlabeledClassInputLabel = `Unlabeled class [${numMatches} matches]`;
> ```

wrap to 80 width

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts, line 403 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/724#-KywDVlVsOH1dKWgpWGx:-KywDVlVsOH1dKWgpWGy:bdom6q6) ([raw file](https://github.com/tensorflow/tensorboard/blob/26ea393839492148dc666129f3313e202d3c114e/tensorboard/plugins/projector/vz_projector/vz-projector-projections-panel.ts#L403)):*
> ```XML
>       return stats.name;
>     });
>     
> ```

remove leading whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/724)*

**Comment by dsmilkov** [comment]
Reviewed 3 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/724)*

**Comment by dsmilkov** [comment]
Thanks! I left a few comments (nothing major) via [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/724). I find it much easier to review larger PRs. Ping me when the comments are addressed and I'll take another look and merge.

Thank you @francoisluus

**Comment by francoisluus** [comment]
@dsmilkov - Concerns in the feedback has been addressed, I'll be sure to conform to these guidelines in the future as well, thanks.

The opening comment in this PR has been updated with observations on the revised branch. Mostly the capturing and propagating of supervision settings has been made more robust, and some attention has been given to improved status messaging for picking the unsupervised class.

**Comment by lmcinnes** [comment]
@francoisluus - this looks fantastic, and was certainly exactly what I had in mind as a use case for semi-supervised t-SNE. I would add that in grounding the theory for ss-tsne I encountered difficulties that eventually resulted in the creation of [UMAP](https://github.com/lmcinnes/umap) which I believe provides the correct theoretical base upon which to build semi-supervision. Semi-supervised UMAP is on the current roadmap, but has not yet been implemented. I would encourage looking into UMAP as a future option.

**Comment by francoisluus** [comment]
@dsmilkov - Superseded by https://github.com/tensorflow/tensorboard/pull/756 , due to excessive conflicts after namespace mods and to propose revision with streamlined layout.

**Pull request closed without merging**
