### PR TITLE
fix-pip-build for missing v1 API

### PR DESCRIPTION
**Pull request by lanpa**
* Motivation for features / changes
The dufault tf-nightly used in the script causes the following error:
```
  File "/tmp/tensorboard/venv2/local/lib/python2.7/site-packages/tensorboard/plugins/scalar/summary.py", line 89, in pb
    import tensorflow.compat.v1 as tf
ImportError: No module named v1
```
* Technical description of changes

* Screenshots of UI changes

* Detailed steps to verify changes work correctly (as executed by you)
`bazel run //tensorboard/pip_package:build_pip_package`
* Alternate designs / implementations considered

### CODE REVIEW

**Comment by nfelt** [comment]
The issue is a breakage in `tf-nightly` which I've sent a PR to fix already: https://github.com/tensorflow/tensorflow/pull/24867

I don't think we're quite ready to move the pip build testing to run against only the TF 2.0 preview pip package, but for now you can use the tf-nightly build from 20190104 locally and that should still work.

**Comment by wchargin** [comment]
Thanks for the pull request! The problem that you’re seeing is a bug in
`tf-nightly` for which we’ve already submitted an upstream patch:

<https://github.com/tensorflow/tensorflow/pull/24867>

In the meantime, installing `tf-nightly==1.13.0.dev20190104` prior to
installing TensorBoard should suffice as a workaround. Depending on the
TF 2.0 preview would be a major breaking change in TensorBoard, so I’m
not sure that we want to do that due to work around a temporary bug.
Also, it looks like the current 2.0 preview doesn’t have a python3
distribution.

I can confirm that the Pip package smoke test works on 20190104 and
fails on latest (20190114), so I can create a PR to pin against that
working version of tf-nightly.

**Comment by lanpa** [comment]
No wonder those tests are failing. Thanks!

**Comment by wchargin** [comment]
Should be fixed as of #1758.

**Pull request closed without merging**
