### PR TITLE
Update PR curve summary op to use tf.one_hot

### PR DESCRIPTION
**Pull request by chihuahua**
Previously, the op had used scatter-related logic that I had introduced as a patch (because scatter_add was unsupported due to tensorflow/tensorflow#11856). This change makes the logic one-hot encode the indices and perform a summation in order to bucket the predictions. This change thus removes variables and control dependencies from the summary op logic, which reduces complexity.

Also, the previous logic to patch scatter_add had been incorrect (`scatter_update` did not sum up values at the same indices), though the test was too simple to catch that. A subsequent PR will make the tests run off of data generated from a demo and thus make the tests more rigorous.

### CODE REVIEW

**Comment by wchargin** [comment]
* How feasible would it be to make a simple test that exercises the currently-buggy behavior?
  * Good catch on noticing this, but why wasn't it noticed until now if the output was wrong? (Was it only introduced in the tf port, so wasn't actually in production?)
  * The changes mentioned in final paragraph should be in a separate PR.

Will review code in a bit.

**Comment by chihuahua** [comment]
@wchargin,
- Done. We just need 2 predictions in the same bin.
- The `scatter_add` formulation worked. My adaptation using tf.gather did not.
- Done.

**Comment by wchargin** [comment]
Ah, I see: the _patch_ to `scatter_add`, not `scatter_add` itself, was the problem. I understand now.

Can you please confirm that the test that you added fails before this commit and passes after it?

**Comment by chihuahua** [comment]
I updated the PR description to note that the _patch_ had been awry.

The test fails before this commit:
```
AssertionError: 
Not equal to tolerance rtol=1e-07, atol=0

(mismatch 20.0%)
 x: array([[ 2.      ,  2.      ,  2.      ,  2.      ,  1.      ,  1.      ,
         1.      ,  1.      ,  0.      ,  0.      ],
       [ 2.      ,  2.      ,  1.      ,  1.      ,  1.      ,  1.      ,...
 y: array([[  2.000000e+00,   2.000000e+00,   2.000000e+00,   2.000000e+00,
          1.000000e+00,   1.000000e+00,   0.000000e+00,   0.000000e+00,
          0.000000e+00,   0.000000e+00],...

----------------------------------------------------------------------
```

and now passes.

**Pull request merged**
