### PR TITLE
Upgrade python3 version in Travis from 3.4 to 3.5

### PR DESCRIPTION
**Pull request by caisq**

### CODE REVIEW

**Comment by caisq** [comment]
Python 3.4 is quite old now. There are bug fixes in python3.5 that will make the life of tensorboard developers easier.

**Comment by chihuahua** [comment]
Tests pass. I am approving. Anyone - feel free to chime in.

**Comment by jart** [comment]
TensorFlow [supports](https://www.tensorflow.org/install/install_linux) Python 3.4 since it's what's provided by Ubuntu 14.04. We're most likely going to need to support Python 3.4 until 2019.

**Comment by wchargin** [comment]
Given that Python 3.5 is forward-compatible with Python 3.4 code, if we keep testing against Python 3.4 then we should have high confidence that TensorBoard also works on Python 3.5, right? I'm not opposed to _adding_ a Python 3.5 target,\* but given that we definitely do want to continue supporting Python 3.4 it doesn't make sense to me that we should switch to testing against Python 3.5 _only_.

\* I'm not opposed to it _on the above grounds_, but I would carefully consider adding it, as it could significancy increase our build latency. If it doesn't, it's fine with me.

**Comment by jart** [comment]
Yes I think it's a fair to assume that if it works in 3.4 it will work in >3.4, until shown otherwise.

**Comment by caisq** [comment]
@jart, OK. I was just thinking that currently the number of TF users who download 3.5 pip wheels is significantly more than those who download 3.4 pip wheels (ping me if you want more detailed data). But you are right about the backward compatibility. So let's close this PR until it becomes necessary.

**Pull request closed without merging**
