### PR TITLE
Cherry picks for TensorBoard 0.1.7

### PR DESCRIPTION
**Pull request by jart**
This patch release proposal grants a semver policy exception to @ioeric by cherry-picking feature code for the TPU Profiling plugin. This seems reasonable to me, since the plugin itself was only introduced quite recently. The rest of the picks are my curation of bug fixes.

Cursory local testing building, installing, and running the pip package look good. Feel free to test on your own. Feel free to request additional picks.

PyPi upload will most likely happen on Monday or Tuesday.

### CODE REVIEW

**Comment by jart** [comment]
@sam-mccall It seems your `~/.gitconfig` is configured to use your personal GMail address, which isn't on record as having signed the CLA. Since these commits are already part of master, I'll have to override the Google Bot. But you might want to consider signing the CLA under your personal address.

**Comment by wchargin** [comment]
> semver policy exception

Not necessary:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.

(semver v2.0.0, item 4: http://semver.org/spec/v2.0.0.html)

@jart We have two pending changes of the form 'include more existing files in the PyPI package." Would you consider cherry-picking them, too? I'm thinking of (a) a fix for #556, and (b) the inclusion of the summary Python APIs (`tensorboard.plugins.*.summary`). Perhaps you want to defer the latter until we create the `tensorboard.summary` module whose `__init__` file pulls from all of the individual plugin summary modules. (I can PR that.)

**Comment by dandelionmane** [comment]
Could we get https://github.com/tensorflow/tensorboard/pull/562 into this PR? I'm planning to try using TensorBoard with non-TensorFlow DL libraries and it would be nice to pip install and have clean APIs.

**Comment by jart** [comment]
Sure. I approved the other PR. Ping me when that goes in, and I'll schlep it in here.

**Comment by jart** [comment]
> Not necessary:
>
> > Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
>
> (semver v2.0.0, item 4: http://semver.org/spec/v2.0.0.html)

@wchargin TensorBoard is major zero sort of like how GMail was Beta in 2009. I see it as a way to over deliver on expectations while maintaining flexibility.

**Comment by dandelionmane** [comment]
I LGTM'd the other PR.

**Comment by wchargin** [comment]
> Ping me when that goes in, and I'll schlep it in here.

@jart :bell: :-)

**Comment by jart** [comment]
Wonderful. I'll integrate that change by end of day.

**Comment by jart** [comment]
Is it OK if the text plugin delegates don't get included? That API was added recently and it didn't apply cleanly to this branch. PTAL @ b1cef0de60eadf78f66aea789669bdbdb7cb31b6.

**Comment by wchargin** [comment]
Fine with me.

**Comment by jart** [comment]
Terrific. I'm actually really happy that we're adding these delegates to the 0.1 release. It's a trivial change and fills in the gaps of what was originally planned and will help users avoid unnecessary refactoring. As soon as Travis goes green, I'll upload to the cheese shop.

**Comment by jart** [comment]
Terrific. I'm actually really happy that we're adding these delegates to the 0.1 release. It's a trivial change that fills in the gaps of what was originally planned and will help users avoid unnecessary refactoring. As soon as Travis goes green, I'll upload to the cheese shop.

**Comment by wchargin** [comment]
Agreed. Thank you for managing the cherry-picks and being our cheesemonger.

**Comment by jart** [comment]
Cheesemonger? You're breaking my heart William with these honorific titles. I'm just doing a small service to the community, helping these prompt releases go smoothly.

**Comment by jart** [comment]
TensorBoard 0.1.7 is now in the wild.

- [Release notes](https://github.com/tensorflow/tensorboard/releases/tag/0.1.7)
- [PyPi package](https://pypi.python.org/pypi/tensorflow-tensorboard/0.1.7)

cc: @ioeric

**Comment by ioeric** [comment]
Thank you very much for the cherry picks and the new release!

**Pull request merged**
