### PR TITLE
docs: add bind_all to allow docker access

### PR DESCRIPTION
**Pull request by danielsiwiec**
This addresses #4169

This allows the local browser to access tensorboard running inside docker, as the guide does. Without this, tensorboard UI will not be accessible from outside the container

### CODE REVIEW

**Review by wchargin — COMMENTED** [review]
Hi @danielsiwiec! Thanks for the contribution. Can confirm that this is
fix is necessary and sufficient for use in Docker. That said, for
everyone else, this isn’t necessary, so it’s at best superfluous and at
worst an unintended privilege expansion, since the `--bind_all` will
cause their TensorBoard to be exposed to the local network.

Could we perhaps instead update the paragraph at the top of the Setup
section? Something like

> **For Docker users:** In case you are running […] TensorBoard's port.
> Also, pass `--bind_all` to `%tensorboard` to expose the port outside
> the container.

or similar. I’d also be okay with an inline note next to the paragraphs
that you’ve modified, if you prefer that, as long as the experience for
non-Docker users isn’t too cluttered.

**Comment by danielsiwiec** [comment]
@wchargin - you're right. the fix only applies to Docker. I like your idea - let me update the PR to have a paragraph at the top instead

**Comment by danielsiwiec** [comment]
@wchargin done

**Comment by wchargin** [comment]
@googlebot I consent.

**Review by wchargin — APPROVED** [review]
@danielsiwiec: Great! I’ve removed a couple line breaks to make it
clearer where the “For Docker users” comment begins and ends, but this
looks good. Will merge once CI passes. Thank you!

**Comment by danielsiwiec** [comment]
@googlebot I consent.

**Pull request merged**
