### PR TITLE
Initial hparams frontend impl

### PR DESCRIPTION
**Pull request by erzel**

### CODE REVIEW

**Comment by erzel** [comment]
@jart, @nfelt, @chihuahua 

Here is the code that showed the demo today. tf-hparams-dashboard.html is the main code (the other parts just hook it up to TB and add tha vaadin-grid dependency). The code is still pretty 'experimental': I was going to go over it and shape it for a proper PR; this is just to show you what I'm thinking of doing. Please take a look and let us know how do you think we should proceed.

 Erez.

**Comment by erzel** [comment]
@mmilanifard Here's the PR for the demo of the HParams plugin.

**Comment by jart** [comment]
```
404 GET /tf-hparams-dashboard/demo/data/plugin/hparams/session_groups?request=%7B%22colParams%22%3A%5B%7B%22hparam%22%3A%22initial_temperature%22%2C%22filterDiscrete%22%3A%5B310%2C350%5D%7D%2C%7B%22hparam%22%3A%22ambient_temperature%22%2C%22filterDiscrete%22%3A%5B270%2C310%2C350%5D%7D%2C%7B%22hparam%22%3A%22heat_coefficient%22%2C%22filterDiscrete%22%3A%5B0.001%2C0.005%5D%7D%2C%7B%22metric%22%3A%7B%22tag%22%3A%22temperature%2Fcurrent%2Fscalar_summary%22%7D%2C%22filterInterval%22%3A%7B%22minValue%22%3A-1.7976931348623157e%2B308%2C%22maxValue%22%3A1.7976931348623157e%2B308%7D%7D%2C%7B%22metric%22%3A%7B%22tag%22%3A%22temperature%2Fdifference_to_ambient%2Fscalar_summary%22%7D%2C%22filterInterval%22%3A%7B%22minValue%22%3A-1.7976931348623157e%2B308%2C%22maxValue%22%3A1.7976931348623157e%2B308%7D%7D%2C%7B%22metric%22%3A%7B%22tag%22%3A%22delta%2Fscalar_summary%22%7D%2C%22filterInterval%22%3A%7B%22minValue%22%3A-1.7976931348623157e%2B308%2C%22maxValue%22%3A1.7976931348623157e%2B308%7D%7D%5D%2C%22startIndex%22%3A0%2C%22sliceSize%22%3A1000%7D`
```

I'm noticing this sends some really cryptic

**Comment by ajbouh** [comment]
What's the status of this?

I discovered it while trying to figure out the proper "tensorboard way" of exploring and evaluating sessions with different hyperparameters.

**Comment by jart** [comment]
We're still working on this. We had to move the development effort to our internal repo temporarily. We'll be open sourcing it soon, once it's ready.

**Pull request closed without merging**
