### PR TITLE
update: module "program", removing line 384.

### PR DESCRIPTION
**Pull request by shenfe**
Just remove a useless line which is duplicated with another line below.

* Line 384 is not needed because of line 390.

### CODE REVIEW

**Comment by shenfe** [comment]
> Actually, I think that line 390 is the one that should be removed,
> because line 384 is right next to the comment on line 381 that explains
> what these variables do. Could you amend this PR to keep the earlier
> definition?

Sure, line 384 responds with line 381 indeed. However, the `if` block at line 386-389 has no business with variable `max_attempts`, and just acts as a check of variable `base_port`. That's why I chose to remove line 386.

**Comment by shenfe** [comment]
> 
> 
> I don’t understand—it sounds like we agree that the line at 384 makes
> sense and the line at 390 doesn’t, and that we prefer line 384, so would
> you mind changing the patch to reinstate line 384 and remove line 390?

If we keep line 384 and the code raises an exception after then because of wrong `base_port`, variable `max_attempts` would have been declared as a waste at line 384.

**Comment by wchargin** [comment]
What do you mean by “would have been declared as a waste”?

If performance is your concern, don’t worry about it. A branch and local
variable assignment to one of two integer constants is absolutely free
compared to all the other work that TensorBoard has to do. On the
contrary, colocating the variable with the comment describing it has
real advantages for readers of the code.

**Comment by shenfe** [comment]
> What do you mean by “would have been declared as a waste”?
> 
> If performance is your concern, don’t worry about it. A branch and local
> variable assignment to one of two integer constants is absolutely free
> compared to all the other work that TensorBoard has to do. On the
> contrary, colocating the variable with the comment describing it has
> real advantages for readers of the code.

Alright, it seems that we have some different styles on coding. Anyway, 无伤大雅. Just go ahead and make changes by yourself. Never mind.

**Comment by wchargin** [comment]
Okay, no worries—thanks anyway for the contribution and for bringing
this to our attention! :-)

**Pull request closed without merging**
