### PR TITLE
Upgrade protobuf version in workspace.bzl and setup.py

### PR DESCRIPTION
**Pull request by caisq**
The previous version was very old (3.0.0), which may caused the
following error to occur when the --debugger_data_server_grpc_port
flag is used when launching the tensorboard binary from bazel run.
The version was also inconsistent with the protobuf dependency
version specified in pip_package/setup.py.

This change fixes those inconsistencies.
It also makes the protobuf version consistent with tensorboard.

Also in this change:
* Update grpcio version used by Travis CI.

### CODE REVIEW

**Comment by caisq** [comment]
cc @chihuahua @jart @wchargin 
This change fixes the following type of error in some cases, where the old protobuf version from the bazel workspace, instead of the newer version installed with tensorflow, is picked up during the bazel run.

>     _sym_db.RegisterServiceDescriptor(_EVENTLISTENER)
> AttributeError: 'SymbolDatabase' object has no attribute 'RegisterServiceDescriptor'

**Comment by caisq** [comment]
Gentle ping @jart ?

**Comment by jart** [comment]
TensorBoard uses the same version of protobuf as TensorFlow. Do you think we should upgrade TensorFlow first before upgrading TensorBoard?

**Comment by jart** [comment]
Looks like protobuf was updated upstream in https://github.com/tensorflow/tensorflow/pull/13819. Please sync and I'll merge.

**Comment by caisq** [comment]
@jart The upstream change (https://github.com/tensorflow/tensorflow/pull/13819) is compatible with this PR in its current form. The upstream change upgrades tensorflow's  protobuf pip dependency from 3.3.0 to 3.4.0. This PR does exactly the same upgrade for tensorboard's protobuf pip dependency (see change in `setup.py`). This PR also upgrades tensorboard's protobuf bazel dependency to 3.4.1. The patch version difference should be okay though. 3.4.1 is not available in PyPI yet. When it becomes available, I can upgrade both tensorflow and tensorboard.

So I think the PR is okay as is. WDYT? Thanks.

**Comment by caisq** [comment]
@jart @chihuahua Merge conflict resolved. PTAL.

**Comment by caisq** [comment]
@jart Can we merge this soon if you do not have any remaining concerns?

**Comment by jart** [comment]
I'm sorry this is reporting conflicts. Any chance you can sync to head? Then I'll have it go in right away.

Also is this going to need to go into 1.4.0-rc3? Right now it seems tensorflow 1.4.0rc1 is tracking protobuf 3.3.0 still.

**Comment by caisq** [comment]
@jart I just resolved the conflict.

Yes, this should go into a version of tensorflow that has protobuf>=3.4.0.

**Comment by jart** [comment]
Thank you @caisq.

**Comment by caisq** [comment]
Thanks, @jart!

**Pull request merged**
