### PR TITLE
Make proto build config more sync friendly

### PR DESCRIPTION
**Pull request by jart**
Proto rules also made public in case anyone ever wants to parse their own event log data.

### CODE REVIEW

**Comment by wchargin** [comment]
> Proto rules also made public in case anyone ever wants to parse their own event log data.

Hmm, I'm not sure about this. Protos like `PrCurvePluginData` definitely seem like they should be privately owned by the plugin. (cc @dandelionmane ?)

**Comment by chihuahua** [comment]
Indeed, it seems like plugin-specific protos should be private. Are there plugins that say ML dash or the plugin example repo require access to?

**Comment by wchargin** [comment]
There are not. mldash does not support the vz-projector plugin nor (obviously) the P/R curve plugin.

**Comment by jart** [comment]
Protos are an inherently public thing. We can never make breaking changes even if it's private, because it'll break user data. So making them private doesn't gain us any flexibility. It just makes people go through the Python plugin API, which is already public in the pip package. I say people own their data and formalize reality.

**Pull request merged**
