### PR TITLE
Make tf-tensorboard less hard coded

### PR DESCRIPTION
**Pull request by jart**
This is going to allow our friend in chrisranderson/beholder#4 to build a
custom TensorBoard, without needing to copy the whole of tf-tensorboard.html
into his repository.

### CODE REVIEW

**Comment by wchargin** [comment]
We think alike! #202

**Comment by wchargin** [comment]
Interesting. This and #202 both have points that I like, and perhaps we'd do best to merge them.

I like that you structured this in a way that `//tensorboard/components/tensorboard` has the dependencies, and not `tf-tensorboard`. This makes it easier for people to change the plugin set, without copying as many build rules.

But I'm less happy about the way that `TENSORBOARD_PLUGINS` is exposed as a global that's then implicitly depended on in `tf-tensorboard`. In #202, I let `tf-tensorboard` explicitly ES6-import `DASHBOARDS`, which is cleaner but incurs the build-time dependency.

Do you see a best of both worlds? If not, I think I'd prefer to keep your way, because having the easy, extensible build is probably worth a hack on `window`.

(For what it's worth, my goal is for `tensorboard/components/tensorboard.html` to eventually be built by a Skylark rule that automatically aggregates the right set of plugins and creates your `TENSORBOARD_PLUGINS` JavaScript object. Both your approach and my approach seem compatible with this goal.)

**Comment by jart** [comment]
Just got back from the movies. Wow I totally didn't notice your PR before I sent this one out. If I'm independently coming up with solutions just like yours, then I'm doing something right.

> But I'm less happy about the way that TENSORBOARD_PLUGINS is exposed as a global

One nice thing about the global, is that the Closure Compiler will throw a hard error at compile time if it isn't defined.

> Do you see a best of both worlds? 

I'll take a close look sometime tomorrow.

> (For what it's worth, my goal is for tensorboard/components/tensorboard.html to eventually be built by a Skylark rule that automatically aggregates the right set of plugins and creates your TENSORBOARD_PLUGINS JavaScript object. Both your approach and my approach seem compatible with this goal.)

I agree with that goal.

**Comment by jart** [comment]
@wchargin Is it safe to delete the reload disabling stuff from tf-tensorboard? All it seems to be doing is preventing a timer from calling a `reload()` method that's already empty. Except tf-graph seems to be downloading health pills on reload, so we probably shouldn't be disabling it.

If we get rid of that, we can keep the nice simple map. Any future configuration options tf-tensorboard needs to know, should probably be set as properties on the dashboard web components themselves.

**Comment by wchargin** [comment]
> Is it safe to delete the reload-disabling stuff from tf-tensorboard?

It's safe in the sense that it won't break anything. The argument for keeping it is that plugins that _don't_ reload (like the embeddings projector) or only reload part of their state (like the graph dashboard) may confuse users who click the "reload" button and expect the state to be…well, reloaded. But one could also say that it's the responsibility of these plugins to alert their users that they're not, in fact, reloading. I don't have any strong opinions; cc @dandelionmane and maybe @dsmilkov ?

If there's agreement, using the simple name-to-component map is fine with me.

**Comment by wchargin** [comment]
> One nice thing about the global is that the Closure Compiler will throw a hard error at compile time if it isn't defined.

Good point. (It should do that for imports, too, I hope, but it means that the globals-downsides are not as bad.)

A couple more things on reload-disabling: (a) if we do it, I'd prefer to do it in a separate PR; (b) there are some tests that will need to be changed (`core_test` and some defunct web component tests among them).

**Comment by jart** [comment]
Can we have a property on the components themselves that say, "hideReloadButton" or something?

**Comment by wchargin** [comment]
Yes, we could do that. I'm somewhat reluctant because currently we have a very nice abstraction: each dashboard is rendered as a single Polymer component with no properties provided and no properties read. The only place in which we break this abstraction by interacting with this component is to call `reload`. Adding more features makes the dashboards less of a black box. That said, we can achieve this behavior without adding more extension points if we treat the existence of the `reload` function as the flag: `if (dashboard) dashboard.reload()` becomes `if (dashboard && dashboard.reload) dashboard.reload()`. What do you think @jart @dandelionmane ?

**Comment by dandelionmane** [comment]
Another solution: Let each plugin take control of the symbols in the top-right area. Then each plugin can provide a help link that points to its own README, it can have a reload button if appropriate, it can have its own gearbox settings. The only thing is, if we want to keep the TensorBoard-wide "autoreload" toggle we would need to split the settings pane to have some tensorboard-generic components, which would be messy. Maybe we just let each plugin have the autoreload setting, even though it's really shared?

**Comment by wchargin** [comment]
Looks like there are lots of approaches to resolving the reload-disabled business. How about we revert that change in this CL (as it's orthogonal) and keep the core of what @jart has here? Then I can abandon #202  in favor of this PR.

**Comment by jart** [comment]
Sounds good to me. This CL is sync to head.

**Comment by jart** [comment]
Do we still want to move forward on this?

**Comment by wchargin** [comment]
Yes, as far as I'm aware! It looks like the changes to remove the reload-disabling behavior are still in this PR. Happy to approve once those are reverted.

**Comment by jart** [comment]
PTAL. I made `isReloadDisabled` a property of the dashboard components themselves. No regression in behavior now exists.

**Comment by jart** [comment]
I agree. I tried to make the property be computed properly, but it didn't work, and it probably has something to do with the side effects of these existing methods. You're welcome to take a look into making this more definitional if you feel it's a worthwhile use of your time.

**Pull request merged**
