### PR TITLE
Fixing session_debug_test as device names change in TF

### PR DESCRIPTION
**Pull request by rohan100jain**

### CODE REVIEW

**Comment by wchargin** [comment]
Hi Rohan—could you please write a summary and test plan to explain the background behind this change? (Look at other commits in this repo for examples.)

In particular, in what version of TensorFlow will this naming change take effect? By looking at the Travis build 
failures, it appears that the current code is still correct, and so this shouldn't be merged until TensorFlow nightly has changed.

**Comment by rohan100jain** [comment]
jenkins, test this please

**Comment by jart** [comment]
Saying "test this please" isn't necessary with Travis CI. Try syncing this PR to head and leave a comment once it's green. I'll hit merge.

**Comment by jart** [comment]
Closing in favor of absorbing into #637. Hopefully this should pass at HEAD. Thank you for the contribution.

**Pull request closed without merging**
