### PR TITLE
Projector: Semi-supervised t-SNE

### PR DESCRIPTION
**Pull request by francoisluus**
Integrates/supersedes:
1) #756 Projector: Supervision and metadata editor (semi-supervised t-SNE)
2) #762 Projector: t-SNE perturb v2

https://medium.com/@fpsluus/interactive-supervision-with-tensorboard-9a101c91d3f7

Demo here: http://tensorserve.com:6016
```bash
git clone https://github.com/francoisluus/tensorboard-supervise.git
cd tensorboard-supervise
git checkout 84e9c55c56fc358a1f9a7746d896ccdc62db6128
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6016
```

### Pairwise label similarity priors
Notice the repeating contraction in the below image, relating to repetitively turning supervision on and off, which incorporates the prior probabilities based on pairwise label similarity/dissimilarity when supervision is turned on.
1_5ryfnhag661937c00nabza

#### Semi-supervised t-SNE
Add supervise metadata column selection and unlabeled class input in data-panel, and supervise factor in t-SNE projections-panel. Use available labels to modify t-SNE input similarities so that same-label samples have amplified attraction and different-label samples have attenuated attraction to a degree specified by the supervise factor (0 no supervision, 100 full supervision). Metadata edits immediately update the labels used by t-SNE, which effectively provides interactive supervision by being able to label a continuous semi-supervised t-SNE embedding process.

1. When the supervision slider is set to 0, t-SNE functions exactly as before as the supervision clause is not entered.
2. The supervision slider changes a visible percentage value from 0 to 100, corresponding to label importance values of 0 to 1. The supervision slider sets the label importance value in range [0, 1], where 0 turns off supervision and 1 sets full label importance. The concept of label importance is used from McInnes et al. [1].
3. An unlabeled class label, also known as an ignored label can be specified, which would consider corresponding points as unlabeled points that receive a default pairwise prior probability. The supervision settings in the data panel names this field superviseInput to generalize and allow for other uses of the text field in future, e.g. for other types of supervision.
4. A supervise column specifier gets the metadata column to use to determine which labels the supervision is conducted with.
5. t-SNE does cause some unexpected behavior when choosing a metadata column with many hundreds of classes, then a re-run is required.
6. Changes in the supervision settings are updated first in the dataset class, and then propagated to the TSNE class itself to use in the gradient step function, where a snapshot is made to prevent supervision changes during the step (not 100% sure if deep copy actually happens).
7. The supervision settings may change from step to step, e.g. such that one step may include supervision while the next step is without supervision, i.e. if the user slides the supervision factor from a non-zero value to zero.
8. The metadata editor dropdown-menu is moved below the supervision settings, so that the metadata label field and status messages are paired with the 'Label' button in the row below.
9. The supervision settings only appear for select projections, such as t-SNE in this case, otherwise it is hidden. The supervision settings are moved to the data panel as it may be a common element for multiple supervised projections.
10. Other projections could be added, like the t-SNE successor UMAP, and its semi-supervised version where the supervision settings elements in the data panel can then be reused with only a supervision slider required for the corresponding projections panel.
11. 'Label by' and 'Color by' are moved into the same row for a more compact, yet still neat, data panel.
#### Perturb v2
Now t-SNE perturb works only with mousedown, firing every 0.1 sec randomly offsetting points within their 5% hyperspheres while remaining within the t-SNE hypersphere. This has the effect of producing an even more homogenized spherical uniform distribution upon successive perturbation, with points doing random walks. Now mousedown duration is used to choose the extent of perturbation, and the perturb slider can thus be removed.

1. Behavior remains exactly the same when the perturb button is never clicked.
2. Perturbation of point locations are now performed as a random walk within the bounds of the assumed t-SNE plotting space modeled as a hypersphere.
3. A perturbation step is done uniformly within a small hypersphere, set at 5% of the t-SNE hypersphere size, centered around each point.
4. A randomly chosen perturbation has to place the perturbed point inside the t-SNE hypersphere, so sampling is performed until this condition is met, which should happen at least with probability equal to the inverse proportion of a small 5% hypersphere to its intersection with the t-SNE hypersphere centered on the hypersphere surface. For most points well inside the t-SNE hypersphere the first random perturbation sampling will very likely be valid.
5. The perturb slider is no longer required, as the perturb button alone is enough to apply a random walk of all points as long as it is pressed with visual feedback via the updated projection after every perturbation.
6. The perturbation can happen while t-SNE is running or when it is paused, as long as it hasTSNERun.
7. The perturbation fires immediately on mousedown, then it fires approximately every 0.1 seconds as a new perturbation calculation.
8. The t-SNE embedding may have slight asymmetry to begin with, but it is assumed that its dimensions are approximately normalized with respect to one another, otherwise the hypersphere assumption will not hold.
9. Perturbation keeps points within the approximate hypersphere and the random walks produce a more uniform distribution of the points and make the t-SNE more spherical.

### Semi-supervised t-SNE
1. The pairwise prior probabilities are set according to McInnes et al. [1], where neighbors are used and where current labeling is not representative of class prior probabilities.
2. However, the normalization is computed over all pairwise prior probabilities according to Yang et al. [2], and not only within neighborhoods as in [1].
3. The naive pairwise prior probability is 1/N, which is used for interactions with unlabeled class samples.
4. For different label pairs we subtract superviseFactor/otherCount from the naive prior, where otherCount is the number of samples with a different label, so if superviseFactor is sufficiently large the attractive force between two samples with different labels will be set to epsilon. Attractive force is easily zeroed between different labeled samples.
5. For same-label pairs we add superviseFactor/sameCount to the naive prior, and the maximum sum is limited close to 1. Attractive force scales up more gradually between same-label pairs.

### Data and projection panel before & after
screen shot 2017-12-12 at 3 03 35 pmscreen shot 2017-12-12 at 3 04 10 pm
screen shot 2017-12-12 at 3 06 08 pmscreen shot 2017-12-12 at 3 05 33 pm

### Color-by views
screen shot 2017-12-12 at 3 24 07 pmscreen shot 2017-12-12 at 3 24 58 pm
screen shot 2017-12-12 at 3 25 45 pm

### Supervision settings status messages
screen shot 2017-11-20 at 6 31 06 pm
screen shot 2017-11-20 at 6 30 49 pm
screen shot 2017-11-20 at 6 31 22 pm
screen shot 2017-11-20 at 6 31 33 pm
screen shot 2017-11-20 at 6 31 57 pm
screen shot 2017-11-20 at 6 32 18 pm
screen shot 2017-11-20 at 6 32 59 pm

### Semi-Supervised t-SNE of McInnes et al. [1]

From https://github.com/lmcinnes/sstsne/blob/master/sstsne/_utils.pyx :
```python
for i in range(n_samples):
    sum_Pi = 0
    if using_neighbors:
        for k in range(K):
            j = neighbors[i, k]
            n_same_label = label_sizes[labels[i] + 1]
            n_other_label = n_samples - n_same_label - n_unlabelled
            if rep_samples:
                ...
            else:
                if labels[i] == -1 or labels[j] == -1:
                    prior_prob = 1.0 / n_samples
                elif labels[j] == labels[i]:
                    prior_prob = min((1.0 / n_samples) + (label_importance / n_same_label), 1.0 - EPSILON_DBL)
                else:
                    prior_prob = max((1.0 / n_samples) - (label_importance / n_other_label), EPSILON_DBL)
            P[i, j] *= prior_prob
            sum_Pi += P[i, j]
        for k in range(K):
            j = neighbors[i, k]
            P[i, j] /= sum_Pi
```

### Attraction normalization of Yang et al. [2]

From Yang et al. [1] the attractive and repulsive forces in weighted t-SNE are balanced with a connection scalar:

where the connection scalar is given as 
The issue here is that if the sum of the prior probabilities are small, then the effective gradient gets scaled down accordingly, which is the case here with a nominal prior of 1/N. So we normalize the gradient size by dividing with the sum of prior probabilities and leaving the repulsion normalization unaffected:

Note that the result here is shown for weighted t-SNE, but it holds for normal t-SNE and its Barnes-Hut implementation.

```typescript
    let sum_pij = 0;
    let forces: [number[], number[]][] = new Array(N);
    for (let i = 0; i < N; ++i) {
      let pointI = points[i];
      if (supervise) {
        var sameCount = labelCounts[labels[i]];
        var otherCount = N - sameCount - unlabeledCount;
      }
      // Compute the positive forces for the i-th node.
      let Fpos = this.dim === 3 ? [0, 0, 0] : [0, 0];
      let neighbors = this.nearest[i];
      for (let k = 0; k < neighbors.length; ++k) {
        let j = neighbors[k].index;
        let pij = P[i * N + j];
        // apply semi-supervised prior probabilities
        if (supervised) {
          if (labels[i] == unlabeledClass || labels[j] == unlabeledClass) {
            pij *= 1. / N;
          }
          else if (labels[i] != labels[j]) {
            pij *= Math.max(1. / N - superviseFactor / otherCount, 1E-7);
          }
          else if (labels[i] == labels[j]) {
            pij *= Math.min(1. / N + superviseFactor / sameCount, 1. - 1E-7);
          }
          sum_pij += pij;
        }
    
    ...
    
    let A = 4 * alpha;
    if (supervised) {
      A /= sum_pij;
    }
    const B = 4 / Z;
```

### References
[1] Leland McInnes, Alexander Fabisch, Christopher Moody, Nick Travers, "Semi-Supervised t-SNE using a Bayesian prior based on partial labelling", https://github.com/lmcinnes/sstsne. 2016.

[2] Yang, Zhirong, Jaakko Peltonen, and Samuel Kaski. ["Optimization equivalence of divergences improves neighbor embedding"](http://proceedings.mlr.press/v32/yange14.pdf). International Conference on Machine Learning. 2014.

### CODE REVIEW

**Comment by francoisluus** [comment]
@chihuahua please add @dsmilkov as reviewer, since this is a continued review of #756, thanks.

**Comment by harveyslash** [comment]
Any plans to add them to the standalone projector ? 
It is sometimes more helpful to use it outside of all of tensorflow 
E.g. https://github.com/harveyslash/TSNE-Embedding-Visualisation

**Comment by dsmilkov** [comment]
:lgtm: Great work as always. Left a couple comments, but nothing major. I've seen this code 3 times by now (in other PRs) :)

---

Review status: 0 of 7 files reviewed at latest revision, 3 unresolved discussions.

---

*[tensorboard/plugins/projector/vz_projector/bh_tsne.ts, line 335 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/811#-L1TFm4eK_lmAHL89kxD:-L1TFm4eK_lmAHL89kxE:bdom6q6) ([raw file](https://github.com/tensorflow/tensorboard/blob/3813c6f99667bcd1aaa5b4e597b815f8ac5fb139/tensorboard/plugins/projector/vz_projector/bh_tsne.ts#L335)):*
> ```XML
>     for (let i = 0; i < N; ++i) {
>       let area = 0;
>       
> ```

remove leading whitespace

---

*[tensorboard/plugins/projector/vz_projector/data.ts, line 312 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/811#-L1TGU7B3Gi0RnIBR-Bb:-L1TGU7B3Gi0RnIBR-Bc:b-15fvlt) ([raw file](https://github.com/tensorflow/tensorboard/blob/3813c6f99667bcd1aaa5b4e597b815f8ac5fb139/tensorboard/plugins/projector/vz_projector/data.ts#L312)):*
> ```XML
>     let opt = {epsilon: learningRate, perplexity: perplexity, dim: tsneDim};
>     this.tsne = new TSNE(opt);
>     this.tsne.setSupervision(this.superviseLabels, this.superviseInput);
> ```

Why not provide the supervise params in the c-tor of T-SNE? Or was the idea to keep the option to dynamically change supervision while its running? Either way is fine - i was just curious.

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts, line 404 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/811#-L1TFyYVaR9CUY4kn4uu:-L1TFyYVaR9CUY4kn4uv:bdom6q6) ([raw file](https://github.com/tensorflow/tensorboard/blob/3813c6f99667bcd1aaa5b4e597b815f8ac5fb139/tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts#L404)):*
> ```XML
>       let numMatches = this.projector.dataSet.points.filter(p =>
>           p.metadata[this.superviseColumn].toString().trim() === value).length;
>       
> ```

remove leading whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/811#-:-L1TGkLCK3E2ECKGCF1L:b727ifm)*

**Comment by francoisluus** [comment]
@dsmilkov Corrections made, please try and merge. Travis is failing due to its certificate issues, but the build is successful on my end and in the demo http://tensorserve.com:6016 .

We could set supervision parameters via the t-SNE constructor, though we also need functions to modify these settings after construction. Here I just use these functions to initialize, in lieu of integrating it into the constructor.

The review, corrections and advice is much appreciated. It seems easy to contribute only because of your excellent code base, which makes it a pleasure to add stuff.

Please be on the lookout for one remaining PR I'll be submitting soon, the one for neighborhood selection improvements.

**Comment by feedmari** [comment]
Q: Is this part correctly merged?

**Pull request merged**
