### PR TITLE
Adding the option to build without TensorFlow

### PR DESCRIPTION
**Pull request by ml7**
The new py_binary target is called tensorboard-notf. It uses a
build_with_tf.py file, which exposes a function use_tf() returning True
or False. build_with_tf.py tries to import this use_tf() function from
tf_disabled.py if TensorFlow is set to be disabled, and tf_enabled.py if
TensorFlow is set to be enabled.

Note: I had some difficulties building with Bazel on Windows, please
pardon anything that seems outright silly. Let's work together to fix
any issues and merge this into master!

### CODE REVIEW

**Comment by ml7** [comment]
I signed it!

**Comment by jspisak** [comment]
@jart @martinwicke - cc'ing you guys to bring this to the top of the stack. Thanks for the collaboration on this..

**Comment by orionr** [comment]
@jart, let us know if we can help on this in any way! Thanks.

**Comment by orionr** [comment]
@jart, should I look at getting the CI tests to pass? Just want to check if you'd like to review the structure of this before I dive into fixing tests. Thanks.

**Comment by ml7** [comment]
The main one has been merged! Thanks all - closing this one

**Pull request closed without merging**
