### PR TITLE
update development.md

### PR DESCRIPTION
**Pull request by arp95**
* Motivation for features / changes

While setting up the environment to run tensorboard on my local system, I found certain statements missing which can help the future new developers.

* Technical description of changes

Updated development.md with required statements

* Screenshots of UI changes

* Detailed steps to verify changes work correctly (as executed by you)

* Alternate designs / implementations considered

### CODE REVIEW

**Comment by arp95** [comment]
@wchargin yes that will do. Making those changes.

**Comment by arp95** [comment]
@wchargin please check now.

**Comment by wchargin** [comment]
> To install TensorFlow nightly within the virtualenv, you can simply
> run the following commands at the root of the Tensorboard Git
> repository:

But you can create the virtualenv anywhere you want, and indeed it’s
better _not_ to put it in the Git work tree because then you have to add
it to your `.git/info/exclude`.

I don’t understand—what problem were you hitting that could be resolved
by creating the virtualenv inside the repository rather than elsewhere?

**Comment by arp95** [comment]
@wchargin the problem was, I created the virtualenv at the home location instead of inside the Git repo. Once I did this, the statements didnt execute as needed and I was not able to follow the steps.

**Comment by arp95** [comment]
If I create the virtualenv at home location, then the commands bazel build tensorboard dont make sense. As at that point I am at home location and need to move to the tensorboard repo to do a bazel build.

Although, it is resolved for me, I can close this if you want.

**Comment by wchargin** [comment]
> If I create the virtualenv at home location, then the commands bazel
> build tensorboard dont make sense. As at that point I am at home
> location and need to move to the tensorboard repo to do a bazel build.

You do indeed need to build TensorBoard inside the TensorBoard repo.

That is totally independent of where the virtualenv lives.

For instance, I personally set up TensorBoard like this:

```
$ cd ~/git/  # where I put repositories
$ git clone tensorboard
$ virtualenv ~/virtualenv/tf-1.13.1
$ . ~/virtualenv/tf-1.13.1/bin/activate
(tf-1.13.1) $ pip install -q tensorflow==1.13.1
(tf-1.13.1) $ cd tensorboard
(tf-1.13.1) $ bazel run //tensorboard -- --logdir ~/tmp/tb_data
```

As you can see, my virtualenv is _not_ in the repository, and I only
need to cd into the repository when I actually want to build from it.

**Comment by arp95** [comment]
@wchargin i mentioned the step "cd tensorboard" to make the process more clear. Anyways should i close this now?

**Comment by wchargin** [comment]
Yes, let’s go ahead and close this.

**Pull request closed without merging**
