### PR TITLE
hash bytes not strs in python 3

### PR DESCRIPTION
**Pull request by dvisztempacct**
This fixes issue #1564

### CODE REVIEW

**Comment by dvisztempacct** [comment]
I signed it!

**Comment by dvisztempacct** [comment]
@olicht should be addressed by b0396039ead7c4057e67b01f2f3c0535a6e4d8c0

**Comment by wchargin** [comment]
The underlying problem is that the data types are different in the two
versions of Python. Instead of introducing these different data types
and trying to discern the appropriate behavior later, why not just
construct the values uniformly in the first place?

```diff
diff --git a/tensorboard/plugins/hparams/hparams_demo.py b/tensorboard/plugins/hparams/hparams_demo.py
index a9dc297e..fd57ec9f 100644
--- a/tensorboard/plugins/hparams/hparams_demo.py
+++ b/tensorboard/plugins/hparams/hparams_demo.py
@@ -46,7 +46,7 @@ HEAT_COEFFICIENT_LIST = [0.001, 0.005]
 
 def fingerprint(string):
   m = hashlib.md5()
-  m.update(string)
+  m.update(string.encode("utf-8"))
   return m.hexdigest()
 
 def create_experiment_summary():
@@ -193,9 +193,9 @@ def run_all(logdir, verbose=False):
   for initial_temperature in TEMPERATURE_LIST:
     for ambient_temperature in TEMPERATURE_LIST:
       for heat_coefficient in HEAT_COEFFICIENT_LIST:
-        hparams = {'initial_temperature' : initial_temperature,
-                   'ambient_temperature' : ambient_temperature,
-                   'heat_coefficient' : heat_coefficient}
+        hparams = {u'initial_temperature' : initial_temperature,
+                   u'ambient_temperature' : ambient_temperature,
+                   u'heat_coefficient' : heat_coefficient}
         hparam_str = str(hparams)
         group_name = fingerprint(hparam_str)
         for repeat_idx in xrange(2):
```

**Comment by dvisztempacct** [comment]
@wchargin that should also do the trick :)

**Comment by dvisztempacct** [comment]
@wchargin if you're proposed changes have been merged, i propose that we close this PR!

**Comment by wchargin** [comment]
They haven’t, but I’m happy to do that in #2056 if you prefer. Thanks
for bringing this issue to our attention and proposing a fix!

**Pull request closed without merging**
