### PR TITLE
rust: add macOS Pip package builds

### PR DESCRIPTION
**Pull request by wchargin**
Summary:
This patch adds support for macOS to the build script and the CI
workflow. Remains to be seen how to get around Gatekeeper issues.

Test Plan:

 1. Acquire access to a macOS environment.
 2. Wait for the GitHub Actions workflow to succeed.
 3. Make a new virtualenv.
 4. Download the `rustboard-macos-10.15.zip` artifact.
 5. Unzip it: `unzip rustboard-macos-10.15.zip`.
 6. Install TensorBoard: `pip install tb-nightly`. (If #4429 is not yet
    in nightlies, instead install a Pip package from head.)
 7. Install the downloaded wheel: `pip install *.whl`.
 8. Launch TensorBoard with these flags:

    ```
    tensorboard --logdir ~/tensorboard_data/mnist --bind_all \
        --load_fast --verbosity 0
    ```

    This should print a log line, “Server binary (from Python package):
    [path to venv]/tensorboard_data_server/bin/server”, and the normal
    TensorBoard UI should properly display data.

wchargin-branch: rust-tds-pip-macos

### CODE REVIEW

**Comment by wchargin** [comment]
@psybuzz: You have macOS, right? Would you mind testing this for me with
the instructions in the PR description? The workflow passed, and you can
download the macOS Pip package from here:
<https://github.com/tensorflow/tensorboard/actions/runs/407369663>

Thanks! Let me know if this is any trouble. I don’t anticipate needing
to need much macOS-specific testing in the future once we get this set
up (probably mostly just a sanity check around releases).

**Comment by psybuzz** [comment]
It works!  Notes:

Works both with and without `--bind_all`.  When the flag is present, MacOS shows a security prompt on every launch, the exact same behavior as TB 2.3 on Mac today.
image

pip list includes:
```
tensorboard             2.5.0a0
tensorboard-data-server 0.1.0a0
```

The very first time I launched it, MacOS shows this security prompt, but fortunately it doesn't prompt on subsequent launches.
image

Expected logs:
[2020-12-08T20:04:25Z WARN  rustboard_core::run] `graph_def` events not yet handled

Timing logs show up properly:
```
I1208 12:02:37.844234 123145587474432 timing.py:122] Thread-3[700010ff4000] ENTER GrpcDataProvider.list_scalars
I1208 12:02:37.844406 123145587474432 timing.py:122] Thread-3[700010ff4000]   ENTER build request
I1208 12:02:37.844505 123145587474432 timing.py:122] Thread-3[700010ff4000]   LEAVE build request - 0.000101s elapsed
I1208 12:02:37.844581 123145587474432 timing.py:122] Thread-3[700010ff4000]   ENTER _stub.ListScalars
I1208 12:02:37.845885 123145587474432 timing.py:122] Thread-3[700010ff4000]   LEAVE _stub.ListScalars - 0.001298s elapsed
I1208 12:02:37.845999 123145587474432 timing.py:122] Thread-3[700010ff4000]   ENTER build result
I1208 12:02:37.847448 123145587474432 timing.py:122] Thread-3[700010ff4000]   LEAVE build result - 0.001448s elapsed
I1208 12:02:37.847786 123145587474432 timing.py:122] Thread-3[700010ff4000] LEAVE GrpcDataProvider.list_scalars - 0.003559s elapsed
I1208 12:02:37.852885 123145587474432 _internal.py:113] ::1 - - [08/Dec/2020 12:02:37] "GET /data/plugin/scalars/tags HTTP/1.1" 200 -
[2020-12-08T20:02:38Z INFO  rustboard] Starting load cycle
I1208 12:02:38.614368 123145587474432 timing.py:122] Thread-3[700010ff4000] ENTER GrpcDataProvider.read_scalars
I1208 12:02:38.614618 123145587474432 timing.py:122] Thread-3[700010ff4000]   ENTER build request
I1208 12:02:38.614842 123145587474432 timing.py:122] Thread-3[700010ff4000]   LEAVE build request - 0.000229s elapsed
I1208 12:02:38.614998 123145587474432 timing.py:122] Thread-3[700010ff4000]   ENTER _stub.ReadScalars
I1208 12:02:38.615894 123145587474432 timing.py:122] Thread-3[700010ff4000]   LEAVE _stub.ReadScalars - 0.000893s elapsed
I1208 12:02:38.616083 123145587474432 timing.py:122] Thread-3[700010ff4000]   ENTER build result
I1208 12:02:38.616343 123145587474432 timing.py:122] Thread-3[700010ff4000]   LEAVE build result - 0.000261s elapsed
I1208 12:02:38.616509 123145587474432 timing.py:122] Thread-3[700010ff4000] LEAVE GrpcDataProvider.read_scalars - 0.002166s elapsed
```
and
```
[2020-12-08T20:02:38Z INFO  rustboard] Finished load cycle (372.46311ms)
[2020-12-08T20:02:43Z INFO  rustboard] Starting load cycle
[2020-12-08T20:02:44Z INFO  rustboard] Finished load cycle (257.55973ms)
[2020-12-08T20:02:49Z INFO  rustboard] Starting load cycle
[2020-12-08T20:02:49Z INFO  rustboard] Finished load cycle (287.557821ms)
[2020-12-08T20:02:54Z INFO  rustboard] Starting load cycle
```

Unexpectedly, when `--load_fast` is used along with a logdir that includes npmi data (e.g. the result of running the npmi demo), the `/data/runs` endpoint is broken, and the UI doesn't load any dashboards at all.

```
I1208 12:16:42.312558 123145564491776 _internal.py:113] ::1 - - [08/Dec/2020 12:16:42] "GET /data/runs HTTP/1.1" 500 -
E1208 12:16:42.317636 123145564491776 _internal.py:113] Error on request:
Traceback (most recent call last):
  File ".../site-packages/werkzeug/serving.py", line 323, in run_wsgi
    execute(self.server.app)
  File ".../site-packages/werkzeug/serving.py", line 312, in execute
    application_iter = app(environ, start_response)
  File ".../site-packages/tensorboard/backend/application.py", line 529, in __call__
    return self._app(environ, start_response)
  File ".../site-packages/tensorboard/backend/application.py", line 570, in wrapper
    return wsgi_app(environ, start_response)
  File ".../site-packages/tensorboard/backend/security_validator.py", line 80, in __call__
    return self._application(environ, start_response_proxy)
  File ".../site-packages/tensorboard/backend/path_prefix.py", line 71, in __call__
    return self._application(environ, start_response)
  File ".../site-packages/tensorboard/backend/experiment_id.py", line 76, in __call__
    return self._application(environ, start_response)
  File ".../site-packages/tensorboard/backend/empty_path_redirect.py", line 47, in __call__
    return self._application(environ, start_response)
  File ".../site-packages/tensorboard/backend/application.py", line 593, in wrapper
    return wsgi_app(environ, start_response)
  File ".../site-packages/tensorboard/backend/application.py", line 552, in _route_request
    return self.exact_routes[clean_path](environ, start_response)
  File ".../site-packages/werkzeug/wrappers/base_request.py", line 238, in application
    resp = f(*args[:-2] + (request,))
  File ".../site-packages/tensorboard/plugins/core/core_plugin.py", line 185, in _serve_runs
    self._data_provider.list_runs(ctx, experiment_id=experiment),
  File ".../site-packages/tensorboard/data/grpc_provider.py", line 62, in list_runs
    res = self._stub.ListRuns(req)
  File ".../site-packages/grpc/_channel.py", line 923, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File ".../site-packages/grpc/_channel.py", line 826, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INTERNAL
	details = "failed to read run data for Run("npmi_demo/run_2")"
	debug_error_string = "{"created":"@1607458602.307608000","description":"Error received from peer ipv6:[::1]:53196","file":"src/core/lib/surface/call.cc","file_line":1063,"grpc_message":"failed to read run data for Run("npmi_demo/run_2")","grpc_status":13}
```

Let me know if there's anything else you'd like to try on MacOS!

**Comment by psybuzz** [comment]
Ah, I didn't mention in the earlier comment but yes, I can confirm it does print:

```
I1208 12:16:35.830465 140734773603776 server_ingester.py:159] Server binary (from Python package): .../site-packages/tensorboard_data_server/bin/server
I1208 12:16:35.832443 140734773603776 server_ingester.py:89] Spawning data server: ['.../site-packages/tensorboard_data_server/bin/server', '--logdir=/Users/luoe/Documents/tf', '--port=0', '--port-file=/var/folders/6g/3y8ydfcd351glr73j6tky6hh00bkvq/T/tensorboard_data_server_yw48m61c/port', '--die-after-stdin', '--verbose']
I1208 12:16:35.846942 140734773603776 server_ingester.py:108] Polling for data server port (attempt 0)
I1208 12:16:35.848942 140734773603776 server_ingester.py:116] Port file contents: None
listening on [::]:53196
```

**Review by psybuzz — APPROVED** [review]

**Comment by wchargin** [comment]
Aweesome; thanks very much for the detailed info!

We might be able to fix the popup about “server” accepting incoming
network connections by binding it to `::1` rather than `::` by default
(the equivalent of not passing `--bind_all`).

> Unexpectedly, when `--load_fast` is used along with a logdir that includes npmi data (e.g. the result of running the npmi demo), the `/data/runs` endpoint is broken, and the UI doesn't load any dashboards at all.

Yep. This is because the NPMI plugin emits summaries that explicitly
have `DATA_CLASS_TENSOR` set, and we don’t handle those yet. You can see
that in the Rust server output:

> thread 'Reloader' panicked at 'not yet implemented: tensor time series not yet supported', tensorboard/data/server/run.rs:108:34

Obviously the proper fix is to support tensors, but in the meantime
I can change this to not panic. I’m not super worried, because most
plugins don’t explicitly set a data class (rather, we infer it at read
time via `data_compat`). So, definiteyl should fix, but not urgent.

**Pull request merged**
