### PR TITLE
[DebuggerV2] Remove extraneous Jasmine dep

### PR DESCRIPTION
**Pull request by caisq**
This unbreaks the Google sync process.

### CODE REVIEW

**Comment by caisq** [comment]
Not ready for review yet. Will send a headsup when ready.

**Comment by wchargin** [comment]
We generally ignore these lints because they only occur at sync time;
note that there are 124 such occurrences across TensorBoard:

```
$ git grep -Hn 'package(' | grep ':1:' | wc -l
124
```

**Comment by caisq** [comment]
@wchargin  Ack. That's what I noticed too. I'll revert this particular diff. cc @ericdnielsen 
I'll fix a BUILD failure that's *actually* the main issue soon by pushing a new commit.

**Comment by caisq** [comment]
Thanks for updating the PR description, @wchargin .

**Pull request merged**
