### PR TITLE
Projector: Metadata editor

### PR DESCRIPTION
**Pull request by francoisluus**
Add a metadata editor to the Projector, which gives the option to modify attributes of selected points. Projector components related to metadata display are refreshed after attribute changes, which also expands the color palette for the modified attribute when a new class is added.

This is very helpful to make alterations and corrections to an existing labeling, although changes are only made in the browser session, but a modified metadata file can be downloaded.

Demo here: http://tensorserve.com:6018
```bash
git clone https://github.com/francoisluus/tensorboard-supervise.git
cd tensorboard-supervise
git checkout 43127d0a33d02ce06fdeb3e39e1e9822cf52c4d4
bazel run tensorboard -- --logdir /home/$USER/emnist-2000 --host 0.0.0.0 --port 6018
```
Supersedes:
1. https://github.com/tensorflow/tensorboard/pull/709 Projector: Metadata editor
2. https://github.com/tensorflow/tensorboard/pull/739 Projector: Metadata editor (closed due to too many conflicts with vz_projector namespace changes)

Superseded by https://github.com/tensorflow/tensorboard/pull/756, which integrates the metadata editor and supervision. Though this PR may be merged first and then #756 as there likely shouldn't be any conflicts.

@dsmilkov - This is currently the best version of the metadata editor to merge. Simplified the metadata editor status messaging, but we could consider using existing sample sizes of applied labels in future.

### Design and behavior
1. The metadata editor uses a new 'Edit by' dropdown-menu and adds a paper-input for typing label name and a paper-button to label selected points with provided label.
2. A metadata download button is added that downloads modified metadata as a .tsv file.
3. The label button is disabled if no selection has been made, or if no label has been specified, or if a numeric label is required but not provided.
4. Multiline floating label is set for the metadata label paper-input to accommodate status messaging for longer labels.
5. A metadata search is done to find the number of existing samples with the specified label.
6. Projector components related to metadata display are refreshed after attribute changes, which also expands the color palette for the modified attribute when a new class is added.
7. _metadataChanged()_ is invoked in the projector after a metadata edit, which normally resets the attribute choices in the data panel and inspector panel. It is proposed that if there is an existing selection it should be retained if it is valid choice, which means that if another metadata file is loaded and it contains the selection it would be preferred.

### Data panel before
screen shot 2017-11-19 at 5 17 51 pm

### Data panel with metadata editor
screen shot 2017-12-11 at 4 07 10 pm
screen shot 2017-12-11 at 4 07 27 pm
screen shot 2017-12-11 at 4 08 11 pm

### Status updates in metadata editor
screen shot 2017-12-11 at 4 08 59 pm
screen shot 2017-12-11 at 4 09 15 pm
screen shot 2017-12-11 at 4 09 28 pm
screen shot 2017-12-11 at 4 09 47 pm
screen shot 2017-12-11 at 4 10 11 pm
screen shot 2017-12-11 at 4 11 21 pm
screen shot 2017-12-11 at 4 11 40 pm

### CODE REVIEW

**Comment by nsthorat** [comment]
This is a wonderful change. Thank you for the detailed notes and screenshots, this really makes the review quite easy :)

One high level comment:

PointMetadata also contains a type: https://github.com/tensorflow/tensorboard/blob/master/tensorboard/plugins/projector/vz_projector/data.ts#L20

What do you think of enforcing the type? This way, you wont run into mixing and matching problems when we try to do things like coloring by a metadata field by a continuous value.

---

Review status: 0 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts, line 133 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/753#-L-m7BxQ3uQL1YQGppSx:-L-m7BxQ3uQL1YQGppSy:b4rbc8b) ([raw file](https://github.com/tensorflow/tensorboard/blob/b01b4647ca2f23630893bde51662fa830647a3bb/tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts#L133)):*
> ```XML
> 
>     this.updateMetadataUI(this.spriteAndMetadata.stats, this.metadataFile);
>     
> ```

remove this blank line

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts, line 135 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/753#-L-m9DfmM-bZHn7tdSNU:-L-m7DV3lGET_3WMjG5q:bx8n7u9) ([raw file](https://github.com/tensorflow/tensorboard/blob/b01b4647ca2f23630893bde51662fa830647a3bb/tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts#L135)):*
> ```XML
>     
>     if (this.selectedColorOptionName == null || this.colorOptions.filter(c =>
>         c.name == this.selectedColorOptionName).length == 0) {
> ```

use "===" everywhere except for "== null".

=== is exact equality, == will do an implicit cast (so when you check null it will also check undefined)

here and below

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts, line 254 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/753#-L-m9F6W81vrI30q_Jbv:-L-m9F6W81vrI30q_Jbw:b4rbc8b) ([raw file](https://github.com/tensorflow/tensorboard/blob/b01b4647ca2f23630893bde51662fa830647a3bb/tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts#L254)):*
> ```XML
>     let selectionSize = this.selectedPointIndices.length + 
>         this.neighborsOfFirstPoint.length;
>     
> ```

remove this blank line

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts, line 264 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/753#-L-m9V-OQWBwTCbyV0GI:-L-m9V-OQWBwTCbyV0GJ:bqhvuwp) ([raw file](https://github.com/tensorflow/tensorboard/blob/b01b4647ca2f23630893bde51662fa830647a3bb/tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts#L264)):*
> ```XML
>         }
>         else {
>           this.metadataEditorInputLabel = 
> ```

remove trailing space

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts, line 301 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/753#-L-m9W0jlIPaiA3mQUQA:-L-m9W0jlIPaiA3mQUQB:b-d66irx) ([raw file](https://github.com/tensorflow/tensorboard/blob/b01b4647ca2f23630893bde51662fa830647a3bb/tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts#L301)):*
> ```XML
>         this.projector.dataSet.points[i].metadata[this.metadataEditorColumn] =
>         this.metadataEditorInput);
>     
> ```

remove the spaces

---

*[tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts, line 305 at r1](https://reviewable.io:443/reviews/tensorflow/tensorboard/753#-L-m9WnBrF8j3mz70vhp:-L-m9WnBrF8j3mz70vhq:b-d66irx) ([raw file](https://github.com/tensorflow/tensorboard/blob/b01b4647ca2f23630893bde51662fa830647a3bb/tensorboard/plugins/projector/vz_projector/vz-projector-data-panel.ts#L305)):*
> ```XML
>         this.projector.dataSet.points[p.index]
>             .metadata[this.metadataEditorColumn] = this.metadataEditorInput);
>     
> ```

remove the spaces

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/753#-:-L-m9YNtYZav3_8pSevr:b-2cjs3a)*

**Comment by francoisluus** [comment]
@nsthorat Please check the newest corrections, based on your feedback, thanks.

To enforce a number-only metadata column will require checking isNumeric in the ColumnStats, adding a check and extra status message in the metadata editor with a label-button disabling. This is sensible and a relatively minor addition to make, thanks for the suggestion.

As there are some other additions to the metadata editor already integrated into some of the open PRs, such as the metadata context and keybindings, I'd like to add the type-enforcing on top of those to prevent conflicts with existing PRs so as to speed up merging.

Alas, I believe it will be necessary to separate the display column (currently used for metadata editor) and an edited column so that one can edit metadata while viewing other metadata. This becomes important when working with text data where there is no other visual representation available as with images having sprites.

Actually, to be prudent, I think I should make all these additions here to get the metadata editor as solid as possible. Then I'll just fix conflicts for later PRs.

**Comment by francoisluus** [comment]
@nsthorat The metadata editor is now fully fledged and can be merged after inspection, please check the newest demo at http://tensorserve.com:6018 . We could put 'Label by' and 'Color by' next to each other when introducing 'Supervise by', it'll look good I promise.

**Comment by nsthorat** [comment]
:lgtm:

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/tensorflow/tensorboard/753#-:-L05IhVVsJiTRKxVZ3NY:bnfp4nl)*

**Comment by nsthorat** [comment]
Looks like I can't merge this +@chihuahua

**Pull request merged**
