### PR TITLE
support webp

### PR DESCRIPTION
**Pull request by nick008a**
Fixing https://github.com/tensorflow/tensorboard/issues/6428

## Motivation for features / changes
https://github.com/tensorflow/tensorboard/issues/6428

## Technical description of changes

https://docs.python.org/zh-tw/3/library/imghdr.html

### CODE REVIEW

**Comment by bileschi** [comment]
Thankyou @nick008a , can you please test by running TensorBoard locally against the webp images events written via PyTorch and verify that it works?  If so, can you please mention in the "verify" section of the PR description.

Additionally, can you replicate the change in  `metrics_plugin.py`

Thanks again!

**Comment by bmd3k** [comment]
Hi, sorry, I need some help to undertand. 

https://github.com/tensorflow/tensorboard/issues/6428 discusses how tensorboard saves images in JPEG and PNG format and suggests we should save in WEBP instead. But this PR only impacts the serving of images. It seems to assume you have already written the image in WEBP format. Can you explain the discrepancy?

**Comment by bmd3k** [comment]
I see. Would you be able to provide me with some sample files that include logged image events in webp format?

**Comment by bmd3k** [comment]
There hasn't been activity on this PR in a while so I'm closing it. Feel free to reopen when you're ready. Recall that I was hoping you'd provide me with some sample event files that include logged webp images, so I could give your changes a try.

**Pull request closed without merging**
