### PR TITLE
Link correction in ADDING_A_PLUGIN.md

### PR DESCRIPTION
**Pull request by francoisluus**
Corrected link: https://github.com/jart/tensorboard-plugin-example

### CODE REVIEW

**Comment by chihuahua** [comment]
Could you please actually correct the link to https://github.com/tensorflow/tensorboard-plugin-example?

Thank you for correcting!

**Comment by wchargin** [comment]
@chihuahua our previous plan was actually to just have this file link to https://github.com/tensorflow/tensorboard/blob/542ac06be716e8b28114bacfcb02535a608c1e12/tensorboard/plugins/scalar/vz_line_chart/vz-chart-helpers.ts#L155-L169, so that we don't have to keep them in sync.

**Comment by wchargin** [comment]
@chihuahua our previous plan was actually to just have this file link to https://github.com/tensorflow/tensorboard-plugin-example/blob/master/README.md, so that we don't have to keep them in sync.

**Comment by chihuahua** [comment]
Oh yeah, I remember that discussion. A lot of our docs were being checked in, and some had been still in the works.

I diffed the 2 docs, and https://github.com/tensorflow/tensorboard-plugin-example/blob/master/README.md seems like a strictly updated version. Lets just link to that from ADDING_A_PLUGIN.md.

Otherwise, it is confusing to open source users because this comment is present in both:

```
<!-- This document was last reviewed on July 21, 2017. It should be
reviewed occasionally to make sure it stays up-to-date. -->
```

In that case, @francoisluus, feel free to revert your fork. Thank you for noticing this issue though.

**Comment by chihuahua** [comment]
https://github.com/tensorflow/tensorboard/pull/412

**Pull request closed without merging**
