### PR TITLE
Image Summary: Officially start using vectorized EncodePng Op

### PR DESCRIPTION
**Pull request by yatbear**
See https://github.com/tensorflow/tensorboard/pull/6344 for context.

Googlers, see b/276803093 for more details.

Tested internally: cl/570508513

#oncall #summary #image

### CODE REVIEW

**Comment by yatbear** [comment]
cc @rainwoodman

**Comment by yatbear** [comment]
cc @nfelt

**Review by groszewn — APPROVED** [review]
Thanks!

**Comment by rainwoodman** [comment]
Thank you for cleaning this up. Yes this change is safe to merge.

**Pull request merged**
