### PR TITLE
TensorBoard 0.4.0

### PR DESCRIPTION
**Pull request by nfelt**
Cherry-picks for a few bug fixes but otherwise no changes.

See the newly added RELEASE.md for release notes that I prepared, please let me know if there's anything further I should add or remove from them.

### CODE REVIEW

**Comment by jart** [comment]
Nit recommendation: Name the branch "cherry-picks" on your local machine, so you don't need to `git reset --hard HEAD~5` when pulling 0.4 back in after rebase-merge.

**Comment by jart** [comment]
Also note to anyone reading, this is mostly playing catch-up on the branch we created for Q4. There will be no pomp and circumstance with this release because TensorBoard 1.5.0 will come out very soon after this one. We will however document what become available in the 0.4 series for the sake of posterity, per #726.

**Comment by nfelt** [comment]
Hmm, good point about needing to reset, though FWIW having the branch name match since it's the same logical branch works for me (I don't mind local hard resets).

It looks like Travis is just failing on pylint now.  Should I try to find the PR's that fixed those lint errors and cherry-pick those too (or patch in the pylint-fixing parts)?  Or should we just ignore pylint?

**Comment by jart** [comment]
Regarding pylint, we made the mistake last summer of not pinning its version.

I recommend cherry-picking https://github.com/tensorflow/tensorboard/commit/9a2f3b81a820fe5aca2b73e091149454e874f8db before the version tag commit.

```sh
git reset --hard HEAD~1
git cherry-pick 9a2f3b81a820fe5aca2b73e091149454e874f8db
git cherry-pick 641bbce9a94ca67f525424b1758f357432751d04  # git garbage data for your 0.4.0 commit
```

**Comment by jart** [comment]
Also to further elaborate on your question, I do want Travis to stay green on release branches, no matter how old. Our build configuration pins everything because the goal is to have historical revisions permanently buildable forevermore.

**Pull request merged**
