### PR TITLE
graph: no graphdef page UI regression #2725

### PR DESCRIPTION
**Pull request by LakshikkaSithamparanathan**
@stephanwlee can you review this PR?
tensorboard-graph-test

Removed the graph controls.

### CODE REVIEW

**Comment by stephanwlee** [comment]
Hi @LakshikkaSithamparanathan, few things:

1. I ran your branch locally and the problem is still there
image
2. I believe the fix is already on master. #3292.
3. please resolve conflict if you want to move forward with the change.

**Comment by LakshikkaSithamparanathan** [comment]
I have resolved the conflict

**Comment by caisq** [comment]
@LakshikkaSithamparanathan @stephanwlee I understand the current behavior is viewed as a bug. **But**, I'd argue it's a feature (albeit with bad layout). That's because I want the "Choose File" button that allows me to upload a graph.pbtxt file even when tensorboard is started pointing to an empty logdir.

**Comment by caisq** [comment]
OK. Noticed #3004 is already fixed. Never mind.

**Comment by LakshikkaSithamparanathan** [comment]
@stephanwlee I have resolved the previously mentioned conflict.
- And also added another PR for css style issue existing in image dashboard.

**Comment by stephanwlee** [comment]
@LakshikkaSithamparanathan, I am having hard time understanding what this PR is exactly fixing. Can you please detail the repro steps and what/how this PR fixes the issue?

**Comment by stephanwlee** [comment]
> Solves the "fix no data UI" in graph dashboard. I changed the condition check from "PRESENT" to "EMPTY

I still do not get this. What is the issue you are seeing? How can I reproduce the issue? 

> solves css style issue when displaying "No image data was found." in image dashboard.

This is not a problem. I do not think we want to accept that change. Please revert the commit.

**Comment by LakshikkaSithamparanathan** [comment]
> > Solves the "fix no data UI" in graph dashboard. I changed the condition check from "PRESENT" to "EMPTY
> 
> I still do not get this. What is the issue you are seeing? How can I reproduce the issue?
> 

As you said before, the fix is already on master. #3292. Sorry if any inconvenience occurred.

> > solves css style issue when displaying "No image data was found." in image dashboard.
> 
> This is not a problem. I do not think we want to accept that change. Heading in a given document should have higher visual weight than other text. Please revert the commit.

The problem i'm saying is heading in a given document is having lesser visual weight than other text. And I fixed that.

**Comment by stephanwlee** [comment]
I see. Sorry, I misread the phrasing and took the first image as _before the change_. Okay. Can you please drop the first commit and rephrase the PR title and description (more description the better) to better capture your intention?

**Pull request closed without merging**
