### PR TITLE
Update required version of html5lib to 1.0b10

### LINKED ISSUE #588: old html5lib makes pip dysfunctional
html5lib dependency should be updated to 1.0b10

windows 10 x64
Anaconda 5.0.0 with python 3.6.2
install tensorflow-gpu -> tensorboard -> html5lib downgraded -> pip dysfunctional

### PR DESCRIPTION
**Pull request by chihuahua**
Fixes #588.

### CODE REVIEW

**Comment by chihuahua** [comment]
Hey - why do we both require the html5lib library in setup.py and pull it into TensorBoard's workspace?
https://github.com/tensorflow/tensorboard/blob/a856e61d39d231e38d45e32e92b28be596afbb58/third_party/python.bzl#L35

**Comment by chihuahua** [comment]
It seems like we use the archive of html5lib for 2 reasons.

1. Including a license: https://github.com/tensorflow/tensorboard/blob/a856e61d39d231e38d45e32e92b28be596afbb58/tensorboard/pip_package/BUILD#L11
2. Building bleach: https://github.com/tensorflow/tensorboard/blob/a856e61d39d231e38d45e32e92b28be596afbb58/third_party/bleach.BUILD#L19

**Comment by jart** [comment]
> Hey - why do we both require the html5lib library in setup.py and pull it into TensorBoard's workspace?

Because the Bazel build doesn't download dependencies via pip. The setup.py file is used to define what people will download using pip when they install the package, that bazel built and I manually upload to cheese shop.

**Comment by chihuahua** [comment]
Ah - thanks!

**Pull request merged**
