### PR TITLE
cleanup: lint scss formats using prettier

### PR DESCRIPTION
**Pull request by stephanwlee**
🧼We now have scss files in the repo. Lint and pretty format them!

### CODE REVIEW

**Comment by wchargin** [comment]
I support this change. For past such changes, we’ve prettified the files
first, then checked in the lint enforcement separately, such that tests
pass at each commit we can mark the first one as ignored for blame.

**Comment by stephanwlee** [comment]
@wchargin the fix is in #3349 which is why I am not bothering to fix the lint failure in the checks. I will officially ask for review when the PR lands.

**Comment by wchargin** [comment]
Ah, my oversight—sorry! :-)

**Comment by stephanwlee** [comment]
Sorry for not making that clearer in the description 🙇

**Pull request merged**
