### PR TITLE
Add new memoize utility and use it to memoize selector factories

### PR DESCRIPTION
**Pull request by rileyajones**
## Motivation for features / changes
Using non memoized selector factories can lead to awkwardness in tests and slightly lower performance in general.

## Screenshots of UI changes (or N/A)
None

## Alternate designs / implementations considered (or N/A)
We could have used a library instead (for example lodash) but the typing wasn't as good.

### CODE REVIEW

**Review by bmd3k — COMMENTED** [review]
Is there something about these calls to createSelector() that makes them non-memoized? 

You also use the term "selector factories" but I don't see any evidence that these are NgRx selector factories:

https://ngrx.io/api/store/createSelectorFactory

**Comment by rileyajones** [comment]
> Is there something about these calls to createSelector() that makes them non-memoized?
> 
> You also use the term "selector factories" but I don't see any evidence that these are NgRx selector factories:
> 
> https://ngrx.io/api/store/createSelectorFactory

The resulting selectors are memoized, but the function which generates the selector isn't. This will result in a new selector being generated each time which effectively makes them non memoized.

I am referring to these as "selector factories" as that is how the upgrade guide refers to this pattern. https://ngrx.io/guide/migration/v12

**Comment by bmd3k** [comment]
> > Is there something about these calls to createSelector() that makes them non-memoized?
> > You also use the term "selector factories" but I don't see any evidence that these are NgRx selector factories:
> > https://ngrx.io/api/store/createSelectorFactory
> 
> The resulting selectors are memoized, but the function which generates the selector isn't. This will result in a new selector being generated each time which effectively makes them non memoized.
> 
> I am referring to these as "selector factories" as that is how the upgrade guide refers to this pattern. https://ngrx.io/guide/migration/v12


I better understand now. That makes sense. I see createSelectorFactory also requires a memoization function to be specified so I guess it's unsurprising that you'd want to add this.

Is there any way/value to use the ngrx defaultMemoize instead of rolling our own?

> 
> Edit: I guess technically the guide calls them "factory selectors", would you prefer I refer to them that way instead?

No, I don't think that would make things any clearer.

**Review by JamesHollyer — APPROVED** [review]
Cool! Im surprised there is not a built in utility for this now that factories are the recommended option. Thanks for follow up on this. Looks good.

**Comment by rileyajones** [comment]
We could use defaultMemoize but it isn't generic and thus return types are always `unknown`. This could be resolved by wrapping it and casting the output, but I'm not sure I like that any better than my current solution

**Pull request merged**
