### PR TITLE
[profile] Spin a big throbber when loading TraceViewer data.

### PR DESCRIPTION
**Pull request by ioeric**

### CODE REVIEW

**Comment by wchargin** [comment]
Are you aware of [`paper-spinner-lite`](https://www.webcomponents.org/element/PolymerElements/paper-spinner)? cf. the [image](https://github.com/tensorflow/tensorboard/blob/da8db355b64a0954342a0af56fe6eaad2542a203/tensorboard/plugins/image/tf_image_dashboard/tf-image-loader.html#L45) and [scalar](https://github.com/tensorflow/tensorboard/blob/da8db355b64a0954342a0af56fe6eaad2542a203/tensorboard/plugins/scalar/tf_scalar_dashboard/tf-scalar-chart.html#L48) dashboards.

**Comment by ioeric** [comment]
Not really... but the trace viewer here is a standalone app that can't use any other TB components for a few reasons (e.g. polymer import conflict caused by trace_viewer_full.html).

**Comment by wchargin** [comment]
You can't use any standard Polymer components at all? (`paper-spinner` is Polymer, not TensorBoard.) That sounds like something that's worth fixing: we'd certainly like the design to be cohesive with the rest of TensorBoard (and material design as a whole). This PR is a good example: if all dashboards use `paper-spinner` except for the trace viewer, which uses ↻, then the trace viewer stands out.

@jart, what do you think?

**Comment by ioeric** [comment]
The trace viewer is indeed an exception here... We are using a [vulcanized](https://github.com/catapult-project/catapult/tree/vulcanized_traceviewer) trace viewer (it's a long story...) mostly because catapult has a home-grown vulcanizer and third party dependencies, and the vulcanized trace viewer brings its own Polymer which would conflict with the Polymer that TB is using, so we had to make the trace viewer a standalone app and embed it into the profile dashboard as a silo (via iframe).

I understand your concern about the style, and we are trying to keep it cohesive to the rest of TB in the profile dashboard, which is a proper TB component. But we can't really do much about trace viewer... :( However, the spinner being added in this PR would just be displayed on top of the trace viewer UI, which, I hope, would not compromise the user experience too much.

**Pull request merged**
