### PR TITLE
core: upgrade Polymer to v2.7

### PR DESCRIPTION
**Pull request by stephanwlee**
* Motivation for features / changes
Polymer 1 is quite old and we should migrate off to 2 and possibly to 3.
This is partially for its internal deprecation but also to revamp build tooling:
we are currently tied to a process called Vulcanization because we have to
build HTML files.

* Detailed steps to verify changes work correctly (as executed by you)
Ran/clicked/exercised all plugins.

* Warning
Although we tried to thorough in our testing, there may be few visual/functional
regressions. We intend to fix forward those bugs as they are identified. 

* Merge plan: squash

* Commit Message
```
core: update the dependencies with Polymer v2 (#2231)                           
core: bump up JSCompiler langout to ES2015 (#2231)                              
core: use v2 Polymer API (#2231)                                                
core: fixed Plottable CSS issue (#2231)                                         
core: <style> should appear inside template (#2231)                             
cleanup: Replaced paper-menu with paper-listbox (#2231)                         
core: fixed the limit setter (#2231)                                                                                                                                                                                                          
graph: fixed most visual regressions of tf-graph (#2251)                        
graph: fixed tf-graph-icons and moved it for reusability (#2251)                
graph: fix graph node toggle bug (#2251)                                        
graph: fix graph fitting in tf-graph-controls (#2251)                           
graph: Fixed input trace (#2251)                                                
graph: fixed broken context menu (#2251)                                        
graph: fixed info panel buttons (#2251)                                         
graph: fixed remaining global selector (#2251)                                  
core: fixed the Plottable interaction (#2249)                                   
profile: fixed mouse interaction (#2286)                                        
profile: fixed CSS issues (#2286)                                               
profile: fixed hosts not updating issue (#2286)                                 
profile: fix misc issues (#2286)                                                
profile: overview and pipline view fixes (#2286)                                
core: fix the line chart tooltip (#2277)                                        
core: fix the data-loader behavior (#2250)                                      
core: use proper CSS selector syntax for :host (#2250)                          
core: fix dashboard-style slot usage to property "slot" (#2250)                 
cpv: fixed custom templatizer in paginated-view2 (#2273)                        
cpv: Restructure files (#2273)                                                  
cpv: Implement category-paginated-view (#2273)                                  
cpv: Migrate to tf-category-paginated-view (#2273)                              
cpv: Fix test for tf-category-paginated-view (#2273)                            
cpv: Remove unused paginated-view and renamed test (#2273)                      
hparams: fixed CSS and initialization (#2341)                                   
debugger: style fixes (#2341)                                                   
debugger: now works as expected (#2341)                                         
infra: compile TypeScript to ES6 (#2341)                                        
projector: fixes for Polymer 2 (#2341)                                          
what-if: fixes for Polymer 2 (#2341)                                            
image: fix the loader and pagination (#2341)                                    
custom scalars: fixed chart rendering (#2341)                                   
mesh: fix for Polymer 2 (#2341)                                                 
cleanup: removed extreanous logs on tooltip (#2372)                             
test: update webcomponent references in test files (#2343)                      
test: fixed the tf-category-paginated-view (#2343)                              
pr-curve: fix the basic functionalities (#2370)                                 
test: unbreak all the tests (#2396)                                             
core: create a tf polymer lib for polymer deps  (#2396)                         
fixed standalone projector demo (#2396)                                         
core: fix the mirror url (#2402)
core: adopt the Polymer 2 externs (#2419)
```

* WANT_LGTM=all

### CODE REVIEW

**Comment by stephanwlee** [comment]
> sync+build internally is okay with this change?

I was going to do this after the merge but, with your comment, I wanted to take a look at what kind of changes would be required. I tried to follow tomservo process to do so except I noticed something weird starting from https://github.com/tensorflow/tensorboard/commit/b5f45070e8bedac113451cef2bbbc05402c64ce3. We are currently syncing JavaScript files in bazel-genfiles built by `bazel --batch build` but, starting from that commit, I cannot make the Vulcanization put JavaScript in that directory. I tried to see how Tomservo continues to work, with the bazel behavioral change, but I am failing to logically make sense. My current hypothesis is that bazel server running on tomservo is stuck on 0.19 and everything magically is working.

**Comment by wchargin** [comment]
My understanding was that we planned for the commit message to include
pointers to previous pull requests of interest. If that’s still the
case, could you please include a preview of that message in the PR
description? (You may find `git shortlog origin/master..origin/polymer2`
useful as a starting point, though it may have too many entries and may
not include all the PR numbers.)

**Comment by stephanwlee** [comment]
@wchargin good idea. I was going to do that when it was time for squash but that sounds better. It is done!

**Comment by stephanwlee** [comment]
I was able to get the internal sync to work. I think we are ready to merge this soon.
For more information, please refer to cl/256261243.

**Comment by stephanwlee** [comment]
Note that this PR has `WANT_LGTM=all` :D

**Pull request merged**
