### PR TITLE
Fix bad images and other minor text changes

### PR DESCRIPTION
**Pull request by anirudh161**
* Motivation for features / changes

Fixed missing TensorBoard iframes by saving notebook with outputs. Made some minor text changes

### CODE REVIEW

**Comment by stephanwlee** [comment]
@anirudh161 did you mean to add the output cell contents? The change is larger than expected and was wondering if that was intended.

**Comment by anirudh161** [comment]
Yes, that was intentional. I sent out this PR as a workaround for the issue where TensorBoard does not get rendered on tensorflow.org and instead outputs broken iframes. Saving outputs in the notebook prevents DevSite from separately running the code cells in the notebooks and causing broken iframes

**Comment by wchargin** [comment]
@anirudh161: If preserving outputs is intentional, could you please
ensure that this notebook sets `private_outputs: false` so that
`nbfmt.py` knows not to erase them? (cc @lamberta)

**Comment by anirudh161** [comment]
Submitted a new PR (#3468 ) with these and a couple of additional changes. Closing this one

**Pull request closed without merging**
